/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view.persona;

import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStreamImpl;
import javax.imageio.stream.ImageOutputStreamImpl;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import py.gov.itaipu.controlacceso.action.CRUDAction;
import py.gov.itaipu.controlacceso.model.Nacionalidad;
import py.gov.itaipu.controlacceso.model.TipoDocumento;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JDialogTipoDocumento;
import org.jdesktop.observablecollections.ObservableCollections;
import py.gov.itaipu.controlacceso.action.persona.PersonaAction;
import py.gov.itaipu.controlacceso.model.Antecedente;
import py.gov.itaipu.controlacceso.model.Organizacion;
import py.gov.itaipu.controlacceso.model.Persona;
import py.gov.itaipu.controlacceso.test.ImageFrame;
import py.gov.itaipu.controlacceso.test.ShowImage;
import py.gov.itaipu.controlacceso.utils.windows.WindowUtil;
import py.gov.itaipu.controlacceso.view.FileFilterExtension;
import py.gov.itaipu.controlacceso.view.JDialogBuscador;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacion;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacionExterna;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JDialogoNacionalidad;
import py.gov.itaipu.controlacceso.view.visita.JDialogFotografia;

/**
 *
 * @author fboy
 */
public class JDialogPersona extends javax.swing.JDialog {

    private CRUDAction<Nacionalidad> nacionalidadAction;
    private CRUDAction<TipoDocumento> tipoDocAction;
    private CRUDAction<Organizacion> organizacionAction;
    private CRUDAction<Antecedente> antecedenteAction;
    private PersonaAction personaAction;
    private Persona persona;
    private Boolean readOnly;
    private BufferedImage imagePersona;
    private ImageIcon iconoFoto;
    private Image imgFotoPersona;
    private File imgFotoPersonaFile;

    /**
     * Creates new form JDialogPersona
     */
    public JDialogPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        readOnly = false;
        persona = new Persona();
        persona.setAntecedentes(new ArrayList<Antecedente>());
        personaAction = new PersonaAction(persona);
        nacionalidadAction = new CRUDAction(new Nacionalidad());
        tipoDocAction = new CRUDAction(new TipoDocumento());
        organizacionAction = new CRUDAction(new Organizacion());
        antecedenteAction = new CRUDAction(new Antecedente());
        initComponents();
        jComboBoxTipoDocumento.setSelectedItem(tipoDocAction.findByNamedQuery("TipoDocumento.findCI").get(0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listNacionalidades = ObservableCollections.observableList(nacionalidadAction.findAll());
        listTipoDocumento = ObservableCollections.observableList(tipoDocAction.findAll());
        listOrganizaciones = ObservableCollections.observableList(organizacionAction.findAll());
        listAntecedentes = ObservableCollections.observableList(persona.getAntecedentes())
        ;
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxNacionalidad = new javax.swing.JComboBox();
        jComboBoxTipoDocumento = new javax.swing.JComboBox();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jLabelApe = new javax.swing.JLabel();
        jButtonNuevoTipoDoc = new javax.swing.JButton();
        jLabelNomb = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelFechaNac = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jFormattedTextFieldFechaNac = new javax.swing.JFormattedTextField();
        jLabelNAcion = new javax.swing.JLabel();
        jLabelEstCiv1 = new javax.swing.JLabel();
        jLabelEstCiv = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabelNroD = new javax.swing.JLabel();
        jLabelTipDoc = new javax.swing.JLabel();
        jTextFieldNroDoc = new javax.swing.JTextField();
        jLabelOrganizacion = new javax.swing.JLabel();
        jTextFieldOrganizacion = new javax.swing.JTextField();
        jButtonBuscarOrganizacion = new javax.swing.JButton();
        jLabelFoto = new javax.swing.JLabel();
        jButtonTomarFoto = new javax.swing.JButton();
        jButtonCargarFoto = new javax.swing.JButton();
        jButtonNacionalidad = new javax.swing.JButton();
        jButtonNacionalidadEdit = new javax.swing.JButton();
        jButtonEditTipoDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Personas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                JDialogPersona.this.windowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE LA PERSONA");

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/save.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setNextFocusableComponent(jButtonCancelar);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/exit.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxNacionalidad.setNextFocusableComponent(jComboBoxSexo);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listNacionalidades, jComboBoxNacionalidad);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxTipoDocumento.setNextFocusableComponent(jComboBoxNacionalidad);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listTipoDocumento, jComboBoxTipoDocumento);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO" }));
        jComboBoxEstadoCivil.setNextFocusableComponent(jFormattedTextFieldFechaNac);

        jLabelApe.setText("Apellido");

        jButtonNuevoTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/new.jpg"))); // NOI18N
        jButtonNuevoTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTipoDocActionPerformed(evt);
            }
        });

        jLabelNomb.setText("Nombre");

        jTextFieldApellido.setNextFocusableComponent(jTextFieldNroDoc);

        jLabelFechaNac.setText("Fecha de Nacimiento");

        jTextFieldNombre.setNextFocusableComponent(jTextFieldApellido);

        jFormattedTextFieldFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldFechaNac.setNextFocusableComponent(jButtonBuscarOrganizacion);

        jLabelNAcion.setText("Nacionalidad");

        jLabelEstCiv1.setText("Sexo");

        jLabelEstCiv.setText("Estado Civil");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMENINO" }));
        jComboBoxSexo.setNextFocusableComponent(jComboBoxEstadoCivil);

        jLabelNroD.setText("Nro Documento");

        jLabelTipDoc.setText("Tipo Documento");

        jTextFieldNroDoc.setNextFocusableComponent(jComboBoxTipoDocumento);

        jLabelOrganizacion.setText("Organizacion");

        jTextFieldOrganizacion.setEditable(false);

        jButtonBuscarOrganizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscarOrganizacion.setToolTipText("Buscar Organizacion");
        jButtonBuscarOrganizacion.setNextFocusableComponent(jButtonTomarFoto);
        jButtonBuscarOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarOrganizacionActionPerformed(evt);
            }
        });

        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/sin_foto.jpg"))); // NOI18N
        jLabelFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setPreferredSize(new java.awt.Dimension(459, 419));

        jButtonTomarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/CAMARA.png"))); // NOI18N
        jButtonTomarFoto.setText("Tomar Fotografia");
        jButtonTomarFoto.setNextFocusableComponent(jButtonCargarFoto);
        jButtonTomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTomarFotoActionPerformed(evt);
            }
        });

        jButtonCargarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/carpeta_abierta.jpg"))); // NOI18N
        jButtonCargarFoto.setText("Cargar Fotografia");
        jButtonCargarFoto.setNextFocusableComponent(jButtonGuardar);
        jButtonCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarFotoActionPerformed(evt);
            }
        });

        jButtonNacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/new.jpg"))); // NOI18N
        jButtonNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNacionalidadActionPerformed(evt);
            }
        });

        jButtonNacionalidadEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/edit.png"))); // NOI18N
        jButtonNacionalidadEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNacionalidadEditActionPerformed(evt);
            }
        });

        jButtonEditTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/edit.png"))); // NOI18N
        jButtonEditTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTipoDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelNomb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelApe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNroD)
                                    .addComponent(jLabelTipDoc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTipoDocumento, 0, 293, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNroDoc))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonTomarFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCargarFoto)
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstCiv)
                            .addComponent(jLabelEstCiv1)
                            .addComponent(jLabelNAcion)
                            .addComponent(jLabelOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldOrganizacion)
                                .addGap(1, 1, 1))
                            .addComponent(jFormattedTextFieldFechaNac)
                            .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNacionalidadEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomb)
                    .addComponent(jButtonTomarFoto)
                    .addComponent(jButtonCargarFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelApe))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNroD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTipDoc)
                                    .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEditTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNAcion)
                                        .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonNacionalidadEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstCiv1)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstCiv)
                            .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaNac)
                            .addComponent(jFormattedTextFieldFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelOrganizacion)
                                .addComponent(jTextFieldOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonBuscarOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonCancelar)))
                    .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTipoDocActionPerformed
        // TODO add your handling code here:
        TipoDocumento td = (TipoDocumento) jComboBoxTipoDocumento.getSelectedItem();
        JDialogTipoDocumento dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
        dialogTipoDocumento.setTipoDocumento(new TipoDocumento());
        WindowUtil.centerWindow(dialogTipoDocumento);
        dialogTipoDocumento.setVisible(true);
        listTipoDocumento.clear();
        listTipoDocumento.addAll(tipoDocAction.findAll());
            if (dialogTipoDocumento.getTipoDocumento().getId()!=null) {
                jComboBoxTipoDocumento.setSelectedItem(dialogTipoDocumento.getTipoDocumento());
            }else{
                jComboBoxTipoDocumento.setSelectedItem(td);
            }
    }//GEN-LAST:event_jButtonNuevoTipoDocActionPerformed

    public JTextField getjTextFieldNroDoc() {
        return jTextFieldNroDoc;
    }

    
    
    public void cargarDatospersona() {
        jTextFieldApellido.setText(persona.getApellido().toUpperCase());
        jTextFieldNombre.setText(persona.getNombre().toUpperCase());
        jTextFieldNroDoc.setText(persona.getNumeroDocumento().toUpperCase());
        
        if(persona.getOrganizacion()!=null)
            jTextFieldOrganizacion.setText((persona.getOrganizacion().getNombre()));
        
        jFormattedTextFieldFechaNac.setValue(persona.getFechaNacimiento());
        jComboBoxEstadoCivil.setSelectedItem(persona.getEstadoCivil().toUpperCase());
        jComboBoxSexo.setSelectedItem(persona.getSexo().toUpperCase());
        jComboBoxNacionalidad.setSelectedItem(persona.getNacionalidad());
        jComboBoxTipoDocumento.setSelectedItem(persona.getTipoDocumento());
        listAntecedentes.clear();
        if (persona.getAntecedentes() != null) {
                listAntecedentes.addAll(persona.getAntecedentes());
        }
        //Cargar Fotografia
        if (persona.getFotografiaPath()!=null) {
            BufferedImage image;
             try {
                String rutaImagen = persona.getFotografiaPath();
                File fileImagen = new File(rutaImagen) ;
                image = ImageIO.read(fileImagen);
                ImageIcon iconoFoto = new javax.swing.ImageIcon(image);
                jLabelFoto.setIcon(iconoFoto);
            } catch (IOException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
//        if (persona.getFotografia() != null) {
//            ByteArrayInputStream bis = new ByteArrayInputStream(persona.getFotografia());
//            BufferedImage image;
//            try {
//                image = ImageIO.read(bis);
//                iconoFoto = new javax.swing.ImageIcon(image);
//                jLabelFoto.setIcon(iconoFoto);
//            } catch (IOException ex) {
//                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            
//        }



    }

    public Persona getPersona() {
        return persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Boolean getReadOnly() {
        return readOnly;
    }

    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (validacionesNuevaPersona()) {
            
            personaAction.setPersona(persona);
            persona.setApellido(jTextFieldApellido.getText());
            persona.setNombre(jTextFieldNombre.getText());
            persona.setNumeroDocumento(jTextFieldNroDoc.getText());
            persona.setFechaNacimiento((Date) jFormattedTextFieldFechaNac.getValue());
            persona.setEstadoCivil(jComboBoxEstadoCivil.getSelectedItem().toString());
            persona.setSexo(jComboBoxSexo.getSelectedItem().toString());
            persona.setNacionalidad((Nacionalidad) listNacionalidades.get(jComboBoxNacionalidad.getSelectedIndex()));
            persona.setTipoDocumento((TipoDocumento) listTipoDocumento.get(jComboBoxTipoDocumento.getSelectedIndex()));
            guardarImagen(imgFotoPersona, imgFotoPersonaFile);
            
            
            if (persona.getId() != null) {
                personaAction.guardar();
                JOptionPane.showMessageDialog(this, "Se ha guardado con exito los nuevos Datos de Persona", "Info", 1);
            } else {
                personaAction.crear();
                JOptionPane.showMessageDialog(this, "Se ha creado con exito nueva Persona", "Info", 1);
            }
          
            this.dispose();
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private boolean validacionesNuevaPersona() {
        boolean resultado = true;
        if (jTextFieldApellido.getText() == null || jTextFieldApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Apellido es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jTextFieldNombre.getText() == null || jTextFieldNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nombre es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jTextFieldNroDoc.getText() == null || jTextFieldNroDoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nro Documento es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jComboBoxTipoDocumento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Seleccionar el Tipo de Documento", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } /*else if (persona.getOrganizacion()==null || persona.getOrganizacion().getId()==null){
            JOptionPane.showMessageDialog(null, "Seleccionar la Organizacion de la Persona", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } */
        return resultado;
    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void windowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowActivated
        // TODO add your handling code here:
        if (readOnly) {
            jTextFieldApellido.setEditable(false);
            jTextFieldNombre.setEditable(false);
            jTextFieldNroDoc.setEditable(false);
            jFormattedTextFieldFechaNac.setEditable(false);
            jComboBoxEstadoCivil.setEnabled(false);
            jComboBoxNacionalidad.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jButtonBuscarOrganizacion.setVisible(false);
            jComboBoxTipoDocumento.setEnabled(false);
            jButtonGuardar.setVisible(false);
            jButtonCargarFoto.setVisible(false);
            jButtonTomarFoto.setVisible(false);
        }
        
    }//GEN-LAST:event_windowActivated

    private void jButtonCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarFotoActionPerformed
        // TODO add your handling code here:
        File input;
        //Selector de Archivos
        JFileChooser chooser = new JFileChooser();
        //Filtro De Extensiones
        FileFilterExtension filtroExtension = new FileFilterExtension("JPG, JPEG, PNG", new String[] { "JPG", "JPEG", "PNG" });
        chooser.setFileFilter(filtroExtension);
        //Desaparece la opcion TODOS LOS ARCHIVOS
        chooser.setAcceptAllFileFilterUsed(false);
        
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                imgFotoPersonaFile = chooser.getSelectedFile();
                
            ////LA FOTOGRAFIA YA NO SE GUARDA EN LA BD. SE GUARDA EL ARCHIVO Y EL PATH EN EL PROYECTO
            //            RandomAccessFile f;
            // byte[] fotografiaByte = null;
            // f = new RandomAccessFile(chooser.getSelectedFile(), "r");
//                fotografiaByte = new byte[(int) f.length()];
//                f.read(fotografiaByte);
//                persona.setFotografia(fotografiaByte);

            

            try {
                BufferedImage image = ImageIO.read(chooser.getSelectedFile());
                iconoFoto = new javax.swing.ImageIcon(image);
                jLabelFoto.setIcon(iconoFoto);
            } catch (IOException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonCargarFotoActionPerformed

    private void jButtonBuscarOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarOrganizacionActionPerformed
        // TODO add your handling code here:
        JInternalFrameOrganizacion jFrameOrganizacion = new JInternalFrameOrganizacion();
        jFrameOrganizacion.setModoBuscador(true);
        jFrameOrganizacion.setVisible(true);
        JDialogBuscador buscador=new JDialogBuscador(null, rootPaneCheckingEnabled);
        buscador.setSize(jFrameOrganizacion.getSize());
        jFrameOrganizacion.setClosable(false);
        jFrameOrganizacion.setResizable(false);
        jFrameOrganizacion.setTitle("Buscador de organizaciones");
        buscador.getjDesktopPaneBuscador().add(jFrameOrganizacion);
        buscador.setVisible(true);
        if(jFrameOrganizacion.getOrganizacionSeleccionada()!=null){
        persona.setOrganizacion(jFrameOrganizacion.getOrganizacionSeleccionada());
        jTextFieldOrganizacion.setText(persona.getOrganizacion().getNombre());}
    }//GEN-LAST:event_jButtonBuscarOrganizacionActionPerformed

    private void jButtonTomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTomarFotoActionPerformed
        // TODO add your handling code here:
         JDialogFotografia dialogFotografia = new JDialogFotografia(null, rootPaneCheckingEnabled, "CAPTURAR");
         dialogFotografia.setPersona(persona);
         dialogFotografia.setVisible(true);        // TODO add your handling code here:
         if (dialogFotografia.isCapturado()) {
             imgFotoPersona = dialogFotografia.getImg();
             mostrarFotoPersona();
        }
    }//GEN-LAST:event_jButtonTomarFotoActionPerformed

    private void jButtonNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNacionalidadActionPerformed
        // TODO add your handling code here:
        Nacionalidad nac = (Nacionalidad)jComboBoxNacionalidad.getSelectedItem();
        JDialogoNacionalidad dialogNacionalidad = new JDialogoNacionalidad(null, rootPaneCheckingEnabled);
        dialogNacionalidad.setNacionalidad(new Nacionalidad());
        WindowUtil.centerWindow(dialogNacionalidad);
        dialogNacionalidad.setVisible(true);
        listNacionalidades.clear();
        listNacionalidades.addAll(nacionalidadAction.findAll());
        if (dialogNacionalidad.getNacionalidad().getId()!=null) {
            jComboBoxNacionalidad.setSelectedItem(dialogNacionalidad.getNacionalidad());
        }else{
            jComboBoxNacionalidad.setSelectedItem(nac);
        }
    }//GEN-LAST:event_jButtonNacionalidadActionPerformed

    private void jButtonNacionalidadEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNacionalidadEditActionPerformed
        // TODO add your handling code here:
        JDialogoNacionalidad dialogNacionalidad = new JDialogoNacionalidad(null, rootPaneCheckingEnabled);
        dialogNacionalidad.setNacionalidad((Nacionalidad)jComboBoxNacionalidad.getSelectedItem());
        WindowUtil.centerWindow(dialogNacionalidad);
        dialogNacionalidad.setVisible(true);
        listNacionalidades.clear();
        listNacionalidades.addAll(nacionalidadAction.findAll());
        jComboBoxNacionalidad.setSelectedItem(dialogNacionalidad.getNacionalidad());
    }//GEN-LAST:event_jButtonNacionalidadEditActionPerformed

    private void jButtonEditTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTipoDocActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        JDialogTipoDocumento dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
        dialogTipoDocumento.setTipoDocumento((TipoDocumento)jComboBoxTipoDocumento.getSelectedItem());
        WindowUtil.centerWindow(dialogTipoDocumento);
        dialogTipoDocumento.setVisible(true);
        listTipoDocumento.clear();
        listTipoDocumento.addAll(tipoDocAction.findAll());
        jComboBoxTipoDocumento.setSelectedItem(dialogTipoDocumento.getTipoDocumento());
    }//GEN-LAST:event_jButtonEditTipoDocActionPerformed
    
    private void mostrarFotoPersona(){
         
                //REGULAR TAMAÑO    
                Image imageScale =  imgFotoPersona.getScaledInstance(530, 310, imgFotoPersona.SCALE_FAST);
//                ImageIcon iconoFoto = new javax.swing.ImageIcon(imageScale);
                ImageIcon iconoFoto = new javax.swing.ImageIcon(imgFotoPersona);
                jLabelFoto.setIcon(iconoFoto);
                           
    }

    public JComboBox getjComboBoxTipoDocumento() {
        return jComboBoxTipoDocumento;
    }
    
    
     private void guardarImagen(Image img, File file) {
         String string = "fotografias/"+persona.getNumeroDocumento()+".jpg";
         if (img!=null) {
            try {
                    int w = img.getWidth(null);
                    int h = img.getHeight(null);
                    BufferedImage bi = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
                    Graphics2D g2 = bi.createGraphics();
                    g2.drawImage(img, 0, 0, null);
                    g2.dispose();
                    String fileType = string.substring(string.indexOf('.') + 1);
                    ImageIO.write(bi, fileType, new File(string));
                    persona.setFotografiaPath(string);

            } catch (Exception e) {
                       
            }
       }else if(imgFotoPersonaFile!=null){
             try {
                 BufferedImage bi = ImageIO.read(imgFotoPersonaFile);
                 String fileType = string.substring(string.indexOf('.') + 1);
                 ImageIO.write(bi, fileType, new File(string));
                 persona.setFotografiaPath(string);
                 
             } catch (IOException ex) {
                 Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
             }
       }
         
         
         
         
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPersona dialog = new JDialogPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarOrganizacion;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarFoto;
    private javax.swing.JButton jButtonEditTipoDoc;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNacionalidad;
    private javax.swing.JButton jButtonNacionalidadEdit;
    private javax.swing.JButton jButtonNuevoTipoDoc;
    private javax.swing.JButton jButtonTomarFoto;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxNacionalidad;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxTipoDocumento;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelEstCiv;
    private javax.swing.JLabel jLabelEstCiv1;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNAcion;
    private javax.swing.JLabel jLabelNomb;
    private javax.swing.JLabel jLabelNroD;
    private javax.swing.JLabel jLabelOrganizacion;
    private javax.swing.JLabel jLabelTipDoc;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNroDoc;
    private javax.swing.JTextField jTextFieldOrganizacion;
    private java.util.List listAntecedentes;
    private java.util.List listNacionalidades;
    private java.util.List listOrganizaciones;
    private java.util.List listTipoDocumento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
