/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view.administracion.organizacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import py.gov.itaipu.controlacceso.action.CRUDAction;
import py.gov.itaipu.controlacceso.action.persona.PersonaAction;
import py.gov.itaipu.controlacceso.model.Organizacion;
import py.gov.itaipu.controlacceso.model.Persona;
import py.gov.itaipu.controlacceso.model.exception.EntidadExiste;
import py.gov.itaipu.controlacceso.utils.tree.CustomIconRenderer;
import py.gov.itaipu.controlacceso.utils.tree.UtilesArbol;

/**
 *
 * @author fboy
 */
public class JDialogOrganigrama extends javax.swing.JDialog {

    private CRUDAction<Organizacion> organizacionAction;
    private Persona persona;
    private Organizacion area;
    private Organizacion areaPadre;
    private PersonaAction personaAction;
    private Boolean modoBuscador;
    private Object seleccionado;

    /**
     * Creates new form JDialogOrganigrama
     */
    public JDialogOrganigrama(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        modoBuscador = false;
        personaAction = new PersonaAction(new Persona());
        organizacionAction = new CRUDAction<Organizacion>();
        organizacionAction.setEntity(new Organizacion());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPaneOrganigrama = new javax.swing.JScrollPane();
        jTreeOrganigrama = new javax.swing.JTree();
        jTextFieldEmpleadoApellido = new javax.swing.JTextField();
        jButtonPersonaNuevo = new javax.swing.JButton();
        jTextFieldEmpleadoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmpleadoNroDoc = new javax.swing.JTextField();
        jButtonOrganizacionNuevo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAreaNombre = new javax.swing.JTextField();
        jTextFieldEmpleadoOrganizacion = new javax.swing.JTextField();
        jTextFieldAreaPadreNombre = new javax.swing.JTextField();
        jButtonGuardarArea = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonGuardarEmpleado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ORGANIGRAMA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel6.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Empleado");

        jLabel5.setText("Nombre:");

        DefaultMutableTreeNode root = UtilesArbol.crearArbol("ORGANIGRAMA", true);
        jTreeOrganigrama = new JTree(root);
        jTreeOrganigrama.setCellRenderer(new CustomIconRenderer());
        jTreeOrganigrama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTreeOrganigramaMousePressed(evt);
            }
        });
        jTreeOrganigrama.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeOrganigramaValueChanged(evt);
            }
        });
        jScrollPaneOrganigrama.setViewportView(jTreeOrganigrama);

        jTextFieldEmpleadoApellido.setEditable(false);

        jButtonPersonaNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/persona.jpg"))); // NOI18N
        jButtonPersonaNuevo.setText("Nuevo empleado");
        jButtonPersonaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonaNuevoActionPerformed(evt);
            }
        });

        jTextFieldEmpleadoNombre.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Area Interna:");

        jLabel7.setText("Nro Documento:");

        jTextFieldEmpleadoNroDoc.setEditable(false);

        jButtonOrganizacionNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/organizacion.png"))); // NOI18N
        jButtonOrganizacionNuevo.setText("Nueva Organizacion");
        jButtonOrganizacionNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrganizacionNuevoActionPerformed(evt);
            }
        });

        jLabel8.setText("Area:");

        jTextFieldAreaNombre.setEditable(false);
        jTextFieldAreaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaNombreActionPerformed(evt);
            }
        });

        jTextFieldEmpleadoOrganizacion.setEditable(false);

        jTextFieldAreaPadreNombre.setEditable(false);

        jButtonGuardarArea.setText("Guardar");
        jButtonGuardarArea.setEnabled(false);
        jButtonGuardarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarAreaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jButtonGuardarEmpleado.setText("Guardar");
        jButtonGuardarEmpleado.setEnabled(false);
        jButtonGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarEmpleadoActionPerformed(evt);
            }
        });

        jLabel3.setText("Area Superior:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButtonOrganizacionNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPersonaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPaneOrganigrama, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(5, 5, 5)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAreaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldAreaPadreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEmpleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEmpleadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEmpleadoNroDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldEmpleadoOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonGuardarArea, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButtonGuardarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPaneOrganigrama, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jTextFieldEmpleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldAreaPadreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldAreaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGuardarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldEmpleadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldEmpleadoNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmpleadoOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrganizacionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPersonaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeOrganigramaValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeOrganigramaValueChanged
        // TODO add your handling code here:
        if (jTreeOrganigrama.getLastSelectedPathComponent() != null) {
            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeOrganigrama.getLastSelectedPathComponent();
            Object objSel = nodoSeleccionado.getUserObject();
            if (objSel.getClass().getSimpleName().equals("Persona")) {
                persona = (Persona) objSel;
                areaPadre = persona.getOrganizacion();

                jTextFieldEmpleadoApellido.setText(persona.getApellido());
                jTextFieldEmpleadoNombre.setText(persona.getNombre());
                jTextFieldEmpleadoOrganizacion.setText(persona.getOrganizacion().getNombre());
                jTextFieldEmpleadoNroDoc.setText(persona.getNumeroDocumento());
                jTextFieldAreaPadreNombre.setText("");
                jTextFieldAreaNombre.setText("");

            } else if (objSel.getClass().getSimpleName().equals("Organizacion")) {
                persona = null;
                area = (Organizacion) objSel;
                areaPadre = (Organizacion) objSel;

                jTextFieldAreaNombre.setText(areaPadre.getNombre());
                if (area.getOrganizacionPadre() != null) {
                    jTextFieldAreaPadreNombre.setText(areaPadre.getOrganizacionPadre().getNombre());
                }

                jTextFieldEmpleadoApellido.setText("");
                jTextFieldEmpleadoNombre.setText("");
                jTextFieldEmpleadoOrganizacion.setText("");
                jTextFieldEmpleadoNroDoc.setText("");

            }
        }
    }//GEN-LAST:event_jTreeOrganigramaValueChanged

    private void jButtonPersonaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonaNuevoActionPerformed
        // TODO add your handling code here:
        if (areaPadre == null || !esOrganizacion()) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR ORGANIZACION SUPERIOR.", "Error", 0);
        } else {
            persona = new Persona();
            persona.setOrganizacion(areaPadre);

            manejaPersona(true);
            manejaOrganizacion(false);
        }

        //            jTextFieldAreaNombre.setText("");
        //            jTextFieldAreaNombre.setEditable(false);
        //            jTextFieldAreaPadreNombre.setText("");
        //
        //            jTextFieldEmpleadoApellido.setText("");
        //            jTextFieldEmpleadoApellido.setEditable(true);
        //            jTextFieldEmpleadoNombre.setText("");
        //            jTextFieldEmpleadoNombre.setEditable(true);
        //            jTextFieldEmpleadoOrganizacion.setText(areaPadre.getNombre());
        //            jTextFieldEmpleadoNroDoc.setText("");
        //            jTextFieldEmpleadoNroDoc.setEditable(true);
        //
        //            jButtonGuardarArea.setEnabled(false);
        //            jButtonGuardarEmpleado.setEnabled(true);

    }//GEN-LAST:event_jButtonPersonaNuevoActionPerformed

    private void manejaPersona(boolean activa) {
        if (activa) {
            jTextFieldEmpleadoApellido.setText("");
            jTextFieldEmpleadoApellido.setEditable(true);
            jTextFieldEmpleadoNombre.setText("");
            jTextFieldEmpleadoNombre.setEditable(true);
            jTextFieldEmpleadoOrganizacion.setText(areaPadre.getNombre());
            jTextFieldEmpleadoNroDoc.setText("");
            jTextFieldEmpleadoNroDoc.setEditable(true);
            jButtonGuardarEmpleado.setEnabled(true);
        } else {
            jTextFieldEmpleadoApellido.setText("");
            jTextFieldEmpleadoApellido.setEditable(false);
            jTextFieldEmpleadoNombre.setText("");
            jTextFieldEmpleadoNombre.setEditable(false);
            jTextFieldEmpleadoNroDoc.setText("");
            jTextFieldEmpleadoNroDoc.setEditable(false);
            jTextFieldEmpleadoOrganizacion.setText("");
            jButtonGuardarEmpleado.setEnabled(false);
        }
    }

    private void manejaOrganizacion(boolean activa) {
        if (activa) {
            jTextFieldAreaNombre.setText("");
            jTextFieldAreaNombre.setEditable(true);
            jTextFieldAreaPadreNombre.setText(areaPadre.getNombre());
            jButtonGuardarArea.setEnabled(true);
        } else {
            jTextFieldAreaNombre.setText("");
            jTextFieldAreaNombre.setEditable(false);
            jTextFieldAreaPadreNombre.setText("");
            jTextFieldAreaPadreNombre.setText("");
            jButtonGuardarArea.setEnabled(false);

        }
    }

    private boolean esOrganizacion() {
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeOrganigrama.getLastSelectedPathComponent();
        if (!nodoSeleccionado.getUserObject().getClass().getSimpleName().equals("Organizacion")) {
            return false;
        }
        return true;
    }
    private void jButtonOrganizacionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrganizacionNuevoActionPerformed
        // TODO add your handling code here:

        if (areaPadre == null || !esOrganizacion()) {
            List<Organizacion> oPadre = organizacionAction.findByNamedQuery("Organizacion.findOrganizacionPadre");
            if (oPadre.size() > 0) {
                JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR ORGANIZACION SUPERIOR.", "Error", 0);
            }
        } else {
            area = new Organizacion();
            area.setOrganizacionPadre(areaPadre);
            manejaOrganizacion(true);
            manejaPersona(false);

        }

    }//GEN-LAST:event_jButtonOrganizacionNuevoActionPerformed

    private void jTextFieldAreaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaNombreActionPerformed

    private void jButtonGuardarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarAreaActionPerformed
        // TODO add your handling code here:
        if (validarOrganizacion()) {
            area.setNombre(jTextFieldAreaNombre.getText());
            area.setTipoOrganizacion("INTERNA");
            organizacionAction.setEntity(area);
            try {
                organizacionAction.crear();
                areaPadre.getOrganizacionesHijas().add(area);

                JOptionPane.showMessageDialog(this, "Se ha guardado con exito el Area Interna", "Info", 1);
            } catch (EntidadExiste e) {                
                JOptionPane.showMessageDialog(this, "La organización ya existe", "Error", 0);
                return;
            }
            manejaOrganizacion(false);
            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeOrganigrama.getLastSelectedPathComponent();
            //                DefaultMutableTreeNode nodoNuevo = new DefaultMutableTreeNode(area,true);
            //                nodoSeleccionado.add(nodoNuevo);
            //                jTreeOrganigrama.repaint();
            actualizarArbol();
            jTreeOrganigrama.setSelectionPath(new TreePath(nodoSeleccionado.getPath()));
            jTreeOrganigrama.expandPath(new TreePath(nodoSeleccionado.getPath()));
            area = null;
            areaPadre = null;

        }
    }//GEN-LAST:event_jButtonGuardarAreaActionPerformed
    private void actualizarArbol() {
        DefaultMutableTreeNode root = UtilesArbol.crearArbol("ORGANIGRAMA", true);
        jTreeOrganigrama = new JTree(root);
        jTreeOrganigrama.setCellRenderer(new CustomIconRenderer());
        jTreeOrganigrama.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeOrganigramaValueChanged(evt);
            }
        });
        jScrollPaneOrganigrama.setViewportView(jTreeOrganigrama);
    }
    private void jButtonGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoActionPerformed
        // TODO add your handling code here:
        if (validarPersona()) {
            persona.setNombre(jTextFieldEmpleadoNombre.getText());
            persona.setApellido(jTextFieldEmpleadoApellido.getText());
            persona.setNumeroDocumento(jTextFieldEmpleadoNroDoc.getText());
            personaAction.setPersona(persona);
            personaAction.crear();

            JOptionPane.showMessageDialog(this, "Se ha guardado con exito los Datos del Empleado", "Info", 1);
            manejaPersona(false);

            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeOrganigrama.getLastSelectedPathComponent();
            //                DefaultMutableTreeNode nodoNuevo = new DefaultMutableTreeNode(persona,true);
            //                nodoSeleccionado.add(nodoNuevo);
            //                jTreeOrganigrama.repaint();
            actualizarArbol();
            jTreeOrganigrama.setSelectionPath(new TreePath(nodoSeleccionado.getPath()));
            jTreeOrganigrama.expandPath(new TreePath(nodoSeleccionado.getPath()));
            persona = null;

        }
    }//GEN-LAST:event_jButtonGuardarEmpleadoActionPerformed

    private void jTreeOrganigramaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeOrganigramaMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && modoBuscador) {
            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeOrganigrama.getLastSelectedPathComponent();
            seleccionado = nodoSeleccionado.getUserObject();
            this.dispose();
        }
    }//GEN-LAST:event_jTreeOrganigramaMousePressed

    public Object getSeleccionado() {
        return seleccionado;
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (modoBuscador) {
            jButtonPersonaNuevo.setVisible(false);
            jButtonOrganizacionNuevo.setVisible(false);
            jButtonGuardarArea.setVisible(false);
            jButtonGuardarEmpleado.setVisible(false);
        }
    }//GEN-LAST:event_formWindowActivated
    private boolean validarPersona() {
        if (jTextFieldEmpleadoApellido.getText() == null || jTextFieldEmpleadoApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "INGRESE APELLIDO.", "Error", 0);
            return false;
        }
        if (jTextFieldEmpleadoNombre.getText() == null || jTextFieldEmpleadoApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "INGRESE NOMBRE.", "Error", 0);
            return false;
        }
        if (jTextFieldEmpleadoNroDoc.getText() == null || jTextFieldEmpleadoNroDoc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "INGRESE NRO DOCUMENTO.", "Error", 0);
            return false;
        }
        return true;
    }

    private boolean validarOrganizacion() {
        if (jTextFieldAreaNombre.getText() == null || jTextFieldAreaNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "INGRESE NOMBRE DE AREA.", "Error", 0);
            return false;

        }
        return true;
    }

    public Boolean getModoBuscador() {
        return modoBuscador;
    }

    public void setModoBuscador(Boolean modoBuscador) {
        this.modoBuscador = modoBuscador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogOrganigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogOrganigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogOrganigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogOrganigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogOrganigrama dialog = new JDialogOrganigrama(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarArea;
    private javax.swing.JButton jButtonGuardarEmpleado;
    private javax.swing.JButton jButtonOrganizacionNuevo;
    private javax.swing.JButton jButtonPersonaNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPaneOrganigrama;
    private javax.swing.JTextField jTextFieldAreaNombre;
    private javax.swing.JTextField jTextFieldAreaPadreNombre;
    private javax.swing.JTextField jTextFieldEmpleadoApellido;
    private javax.swing.JTextField jTextFieldEmpleadoNombre;
    private javax.swing.JTextField jTextFieldEmpleadoNroDoc;
    private javax.swing.JTextField jTextFieldEmpleadoOrganizacion;
    private javax.swing.JTree jTreeOrganigrama;
    // End of variables declaration//GEN-END:variables
}
