/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view.visita;

import java.awt.Dialog;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintServiceAttributeSet;
import javax.print.attribute.PrintServiceAttributeSet;
import javax.print.attribute.standard.PrinterName;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.observablecollections.ObservableCollections;
import org.krysalis.barcode4j.impl.upcean.UPCABean;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;
import org.krysalis.barcode4j.tools.UnitConv;
import py.gov.itaipu.controlacceso.action.CRUDAction;
import py.gov.itaipu.controlacceso.action.visita.VisitaAction;
import py.gov.itaipu.controlacceso.model.Motivo;
import py.gov.itaipu.controlacceso.model.Organizacion;
import py.gov.itaipu.controlacceso.model.Persona;
import py.gov.itaipu.controlacceso.model.Visita;
import py.gov.itaipu.controlacceso.model.exception.ErrorInesperado;
import py.gov.itaipu.controlacceso.persistence.EntityManagerCA;
import py.gov.itaipu.controlacceso.view.JDialogBuscador;
import py.gov.itaipu.controlacceso.view.TimeRenderer;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JDialogOrganigrama;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacionExterna;
import py.gov.itaipu.controlacceso.view.persona.JInternalFramePersona;

/**
 *
 * @author fboy
 */
public class JDialogConsultaVisitas extends javax.swing.JDialog {

    private VisitaAction visitaAction;
    private TableCellRenderer rendererTime;
    private CRUDAction<Motivo> motivoAction;
    private CRUDAction<Organizacion> organizacionAction;
    private Organizacion organizacionExterna;
    private Persona persona;
    private Persona personaVisitada;
    private Organizacion organizacionVisitada;

    /**
     * Creates new form JDialogConsultaVisitas
     */
    public JDialogConsultaVisitas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        visitaAction = new VisitaAction();
        visitaAction.setVisita(new Visita());
        motivoAction = new CRUDAction<Motivo>(new Motivo());
        organizacionAction = new CRUDAction<Organizacion>(new Organizacion());
        rendererTime = new TimeRenderer();
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resource/img/bandera-paraguay.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        List<Visita> l=new ArrayList<Visita>();
        listVisitas = ObservableCollections.observableList(l);
        try{
            listMotivos = ObservableCollections.observableList(motivoAction.findAll());
            Motivo m=new Motivo();
            m.setNombre("TODOS");
            listMotivos.add(0,m);
        } catch (ErrorInesperado ei) {
            JOptionPane.showMessageDialog(null, "Verfique con el administrador la conexión a la base de datos y vuelva a intentar.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
        try{
            listOrganizacionInternas = ObservableCollections.observableList(organizacionAction.findByNamedQuery("Organizacion.findAllInterna"));
            Organizacion o=new Organizacion();
            o.setNombre("TODAS");
            listOrganizacionInternas.add(0, o);
        } catch (ErrorInesperado ei) {
            JOptionPane.showMessageDialog(null, "Verfique con el administrador la conexión a la base de datos y vuelva a intentar.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jFormattedTextFieldHasta = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservacion = new javax.swing.JTextArea();
        jButtonLimpiarPersonaVisitada1 = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDesde = new javax.swing.JFormattedTextField();
        jButtonLimpiarPersona = new javax.swing.JButton();
        jTextFieldOrganizacionExterna = new javax.swing.JTextField();
        jButtonImprimirListado = new javax.swing.JButton();
        jComboBoxMotivo = new javax.swing.JComboBox();
        jButtonLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonImprimirVisita = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAreaPersonaVisitada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscarOrganizacionExterna = new javax.swing.JButton();
        jButtonBuscarAreaPersona = new javax.swing.JButton();
        jButtonLimpiarOrganizacion = new javax.swing.JButton();
        jButtonBuscarPersona = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPersona = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE VISITAS");
        setBounds(new java.awt.Rectangle(30, 30, 0, 0));
        setPreferredSize(new java.awt.Dimension(1278, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listVisitas, jTableVisitas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${persona.nombre} ${persona.apellido}"));
        columnBinding.setColumnName("Persona");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${persona.organizacion.nombre}"));
        columnBinding.setColumnName("Organizacion");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaIngreso}"));
        columnBinding.setColumnName("Fecha Ingreso");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaSalida}"));
        columnBinding.setColumnName("Fecha salida");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${motivo.nombre}"));
        columnBinding.setColumnName("Motivo");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${personaVisitada.nombre} ${personaVisitada.apellido}"));
        columnBinding.setColumnName("Persona Visitada");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${organizacionInterna.nombre}"));
        columnBinding.setColumnName("Area Visitada");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observacion}"));
        columnBinding.setColumnName("Observacion");
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableVisitas);
        jTableVisitas.getColumnModel().getColumn(2).setCellRenderer(rendererTime);
        jTableVisitas.getColumnModel().getColumn(3).setCellRenderer(rendererTime);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 1270, 342);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Lista de visitas.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 200, 170, 15);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 220, 1260, 10);

        jFormattedTextFieldHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(jFormattedTextFieldHasta);
        jFormattedTextFieldHasta.setBounds(250, 40, 66, 20);

        jTextAreaObservacion.setColumns(20);
        jTextAreaObservacion.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObservacion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(860, 40, 410, 67);

        jButtonLimpiarPersonaVisitada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/clear.jpeg"))); // NOI18N
        jButtonLimpiarPersonaVisitada1.setToolTipText("Buscar Persona");
        jButtonLimpiarPersonaVisitada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarPersonaVisitada1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiarPersonaVisitada1);
        jButtonLimpiarPersonaVisitada1.setBounds(680, 40, 22, 22);

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/exit.png"))); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.setMaximumSize(new java.awt.Dimension(89, 25));
        jButtonCerrar.setMinimumSize(new java.awt.Dimension(89, 25));
        jButtonCerrar.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar);
        jButtonCerrar.setBounds(1150, 230, 125, 25);

        jLabel6.setText("Motivo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 100, 70, 14);

        jFormattedTextFieldDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(jFormattedTextFieldDesde);
        jFormattedTextFieldDesde.setBounds(120, 40, 66, 20);

        jButtonLimpiarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/clear.jpeg"))); // NOI18N
        jButtonLimpiarPersona.setToolTipText("Buscar Persona");
        jButtonLimpiarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiarPersona);
        jButtonLimpiarPersona.setBounds(680, 70, 22, 22);

        jTextFieldOrganizacionExterna.setEditable(false);
        getContentPane().add(jTextFieldOrganizacionExterna);
        jTextFieldOrganizacionExterna.setBounds(120, 70, 150, 22);

        jButtonImprimirListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/printer.png"))); // NOI18N
        jButtonImprimirListado.setText("LISTADO");
        jButtonImprimirListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirListadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimirListado);
        jButtonImprimirListado.setBounds(870, 230, 125, 25);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listMotivos, jComboBoxMotivo);
        bindingGroup.addBinding(jComboBoxBinding);

        getContentPane().add(jComboBoxMotivo);
        jComboBoxMotivo.setBounds(120, 100, 150, 22);

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/clear.jpeg"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setMaximumSize(new java.awt.Dimension(89, 25));
        jButtonLimpiar.setMinimumSize(new java.awt.Dimension(89, 25));
        jButtonLimpiar.setPreferredSize(new java.awt.Dimension(89, 25));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar);
        jButtonLimpiar.setBounds(140, 150, 125, 25);

        jLabel7.setText("Hasta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 40, 50, 14);

        jLabel2.setText("Visitante:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 70, 100, 14);

        jButtonImprimirVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/ficha.png"))); // NOI18N
        jButtonImprimirVisita.setText("IMPRIMIR");
        jButtonImprimirVisita.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonImprimirVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirVisitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimirVisita);
        jButtonImprimirVisita.setBounds(1010, 230, 125, 25);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(89, 25));
        jButtonBuscar.setMinimumSize(new java.awt.Dimension(89, 25));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(89, 25));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(10, 150, 125, 25);

        jLabel3.setText("Desde:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 70, 14);

        jTextFieldAreaPersonaVisitada.setEditable(false);
        getContentPane().add(jTextFieldAreaPersonaVisitada);
        jTextFieldAreaPersonaVisitada.setBounds(510, 40, 150, 22);

        jLabel5.setText("Area/Persona Visitada:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 40, 130, 14);

        jLabel4.setText("Observación:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 40, 110, 14);

        jButtonBuscarOrganizacionExterna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscarOrganizacionExterna.setToolTipText("Buscar Persona");
        jButtonBuscarOrganizacionExterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarOrganizacionExternaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarOrganizacionExterna);
        jButtonBuscarOrganizacionExterna.setBounds(270, 70, 22, 22);

        jButtonBuscarAreaPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscarAreaPersona.setToolTipText("Buscar Persona");
        jButtonBuscarAreaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAreaPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarAreaPersona);
        jButtonBuscarAreaPersona.setBounds(660, 40, 22, 22);

        jButtonLimpiarOrganizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/clear.jpeg"))); // NOI18N
        jButtonLimpiarOrganizacion.setToolTipText("Buscar Persona");
        jButtonLimpiarOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarOrganizacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiarOrganizacion);
        jButtonLimpiarOrganizacion.setBounds(290, 70, 22, 22);

        jButtonBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscarPersona.setToolTipText("Buscar Persona");
        jButtonBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPersona);
        jButtonBuscarPersona.setBounds(660, 70, 22, 22);

        jLabel9.setText("Organización:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 70, 80, 14);

        jTextFieldPersona.setEditable(false);
        getContentPane().add(jTextFieldPersona);
        jTextFieldPersona.setBounds(510, 70, 150, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Criterio de búsqueda.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 170, 15);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 30, 1260, 10);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPersonaActionPerformed
        // TODO add your handling code here:
        JInternalFramePersona jFramePersona = new JInternalFramePersona();
        jFramePersona.setModoBuscador(true);
        jFramePersona.setTitle("Buscador de Personas Externas");
        jFramePersona.setTipoOrganizacionPersona("EXTERNA");
        jFramePersona.setVisible(true);
        JDialogBuscador buscador = new JDialogBuscador(null, true);
        buscador.setSize(jFramePersona.getSize());
        //jFramePersona.setClosable(false);
        jFramePersona.setResizable(false);
        buscador.getjDesktopPaneBuscador().add(jFramePersona);
        buscador.setVisible(true);
        persona = jFramePersona.getPersonaSeleccionada();
        if (persona != null) {
            jTextFieldPersona.setText(persona.getNombre() + ", " + persona.getApellido());
        }
    }//GEN-LAST:event_jButtonBuscarPersonaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Visita v = new Visita();
            Date hasta = null;

            if (jTextAreaObservacion.getText() != null && !jTextAreaObservacion.getText().equals("")) {
                v.setObservacion(jTextAreaObservacion.getText().toUpperCase());
            }

            Motivo motivo = (Motivo) jComboBoxMotivo.getSelectedItem();
            if (motivo.getId() != null) {
                v.setMotivo(motivo);
            }

            v.setPersona(persona);
            v.setPersonaVisitada(personaVisitada);


            if (organizacionVisitada != null && organizacionVisitada.getId() != null) {
                v.setOrganizacionInterna(organizacionVisitada);
            }

            if (jFormattedTextFieldDesde.getText() != null && !jFormattedTextFieldDesde.getText().equals("")) {
                v.setFechaIngreso(((Date) jFormattedTextFieldDesde.getValue()));
            }

            if (jFormattedTextFieldHasta.getText() != null && !jFormattedTextFieldHasta.getText().equals("")) {
                hasta = (Date) jFormattedTextFieldHasta.getValue();
                Calendar cal = Calendar.getInstance(); // creates calendar
                cal.setTime(hasta); // sets calendar time/date
                cal.add(Calendar.HOUR_OF_DAY, 23);
                cal.add(Calendar.MINUTE, 59);
                cal.add(Calendar.SECOND, 59);
                hasta = cal.getTime();

            }

            listVisitas.clear();
            listVisitas.addAll(visitaAction.findByParameters(v, hasta, organizacionExterna, "N"));
        } catch (ErrorInesperado ei) {
            JOptionPane.showMessageDialog(null, "Verfique con el administrador la conexión a la base de datos y vuelva a intentar.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarOrganizacionExternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarOrganizacionExternaActionPerformed

        // TODO add your handling code here:
        JInternalFrameOrganizacionExterna jFrameOrganizacionExterna = new JInternalFrameOrganizacionExterna();
        jFrameOrganizacionExterna.setModoBuscador(true);
        jFrameOrganizacionExterna.setVisible(true);
        JDialogBuscador buscador = new JDialogBuscador(null, true);
        buscador.setSize(jFrameOrganizacionExterna.getSize());
        jFrameOrganizacionExterna.setClosable(false);
        jFrameOrganizacionExterna.setResizable(false);
        jFrameOrganizacionExterna.setTitle("Buscador de organización externa");
        buscador.getjDesktopPaneBuscador().add(jFrameOrganizacionExterna);
        buscador.setVisible(true);
        organizacionExterna = jFrameOrganizacionExterna.getOrganizacionSeleccionada();
        if (organizacionExterna != null) {
            jTextFieldOrganizacionExterna.setText(organizacionExterna.getNombre());
        }

    }//GEN-LAST:event_jButtonBuscarOrganizacionExternaActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        persona = null;
        personaVisitada = null;
        organizacionExterna = null;
        jComboBoxMotivo.setSelectedIndex(0);
        jTextAreaObservacion.setText(null);
        jTextFieldPersona.setText(null);
        jTextFieldAreaPersonaVisitada.setText(null);
        jTextFieldOrganizacionExterna.setText(null);

        jFormattedTextFieldDesde.setText(null);
        jFormattedTextFieldHasta.setText(null);

        listVisitas.clear();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonLimpiarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarPersonaActionPerformed
        // TODO add your handling code here:
        persona = null;
        jTextFieldPersona.setText(null);
    }//GEN-LAST:event_jButtonLimpiarPersonaActionPerformed

    private void jButtonLimpiarOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarOrganizacionActionPerformed
        // TODO add your handling code here:
        organizacionExterna = null;
        jTextFieldOrganizacionExterna.setText(null);
    }//GEN-LAST:event_jButtonLimpiarOrganizacionActionPerformed

    private void jButtonImprimirListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirListadoActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("org.postgresql.Driver");
            Connection conexion = EntityManagerCA.getConexion();
            JasperReport reporte = (JasperReport) JRLoader.loadObject("reports/reporteListadoVisitas.jasper");
            //Parametros
            Map<String, Object> parametros = new HashMap<String, Object>();
            ///Parametros
            if (persona != null && persona.getId() != null) {
                parametros.put("pPersonaText", (Object) (persona.getApellido() + ", " + persona.getNombre()));
                parametros.put("pPersonaId", (Object) persona.getId().intValue());
            }
            if (personaVisitada != null && personaVisitada.getId() != null) {
                parametros.put("pPersonaVisitadaText", (Object) (personaVisitada.getApellido() + ", " + personaVisitada.getNombre()));
                parametros.put("pPersonaVisitadaId", (Object) personaVisitada.getId().intValue());
            }

            if (organizacionExterna != null && organizacionExterna.getId() != null) {
                parametros.put("pOrganizacionText", (Object) organizacionExterna.getNombre());
                parametros.put("pOrganizacionId", (Object) organizacionExterna.getId().intValue());
            }


            if (organizacionVisitada != null && organizacionVisitada.getId() != null) {
                parametros.put("pOrganizacionVisitadaText", organizacionVisitada.getNombre());
                parametros.put("pOrganizacionVisitadaId", organizacionVisitada.getId().intValue());
            }
            Motivo motivo = (Motivo) jComboBoxMotivo.getSelectedItem();
            if (motivo.getId() != null) {
                parametros.put("pMotivoText", (Object) motivo.getNombre());
                parametros.put("pMotivoId", (Object) motivo.getId().intValue());
            }
            if (jTextAreaObservacion.getText() != null && !jTextAreaObservacion.getText().equals("")) {
                parametros.put("pObservacion", (Object) jTextAreaObservacion.getText().toUpperCase());
            }

            if (jFormattedTextFieldDesde != null && !jFormattedTextFieldDesde.getText().equals("")) {
                String vFecha = jFormattedTextFieldDesde.getText().substring(6, 10) + jFormattedTextFieldDesde.getText().substring(3, 5) + jFormattedTextFieldDesde.getText().substring(0, 2);
                parametros.put("pFechaDesde", (Object) vFecha.toUpperCase());
                vFecha = vFecha.substring(6, 8) + "/" + vFecha.substring(4, 6) + "/" + vFecha.substring(0, 4);
                parametros.put("pFechaDesdeText", (Object) vFecha.toUpperCase());
            }
            if (jFormattedTextFieldHasta != null && !jFormattedTextFieldHasta.getText().equals("")) {
                String vFechaH = jFormattedTextFieldHasta.getText().substring(6, 10) + jFormattedTextFieldHasta.getText().substring(3, 5) + jFormattedTextFieldHasta.getText().substring(0, 2);
                parametros.put("pFechaHasta", (Object) vFechaH.toUpperCase());
                vFechaH = vFechaH.substring(6, 8) + "/" + vFechaH.substring(4, 6) + "/" + vFechaH.substring(0, 4);
                parametros.put("pFechaHastaText", (Object) vFechaH.toUpperCase());
            }

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, conexion);

            //            Muestra el Reporte en Pantalla
            JasperViewer jviewer = new JasperViewer(jasperPrint, false);
            jviewer.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
            jviewer.viewReport(jasperPrint, false);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonImprimirListadoActionPerformed

    private InputStream generaBarCode(String codeDigits) {

        while (codeDigits.length() < 11) {
            codeDigits = "0" + codeDigits;
        }

        ByteArrayInputStream bis;
        UPCABean bean = new UPCABean();
        final int dpi = 150;
        bean.setModuleWidth(UnitConv.in2mm(2.0f / dpi));
        bean.setFontSize(2.0);
        bean.doQuietZone(true);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        BitmapCanvasProvider canvas = new BitmapCanvasProvider(out, "image/jpeg", dpi, BufferedImage.TYPE_BYTE_BINARY, false, 0);
        bean.generateBarcode(canvas, codeDigits);
        try {
            canvas.finish();
            out.flush();
        } catch (IOException ex) {
            Logger.getLogger(JDialogVisita.class.getName()).log(Level.SEVERE, null, ex);
        }

        bis = new ByteArrayInputStream(out.toByteArray());
        return bis;
    }

    private void jButtonImprimirVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirVisitaActionPerformed
        // TODO add your handling code here:
        if (jTableVisitas.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una visita", "Error", 0);
            return;
        }
        Visita v = (Visita) listVisitas.get(jTableVisitas.getSelectedRow());
        try {
            InputStream bis = generaBarCode(v.getId().toString());
            Class.forName("org.postgresql.Driver");
            Connection conexion = EntityManagerCA.getConexion();
            JasperReport reporte = (JasperReport) JRLoader.loadObject("reports/reporteTicketVisitas.jasper");
            //Parametros
            Map<String, Object> parametros = new HashMap<String, Object>();
            parametros.put("idVis", (Object) v.getId());
            //Paso el full path del proyecto al reporte para obtener las imagenes.
            java.io.File file = new java.io.File("");
            String abspath = file.getAbsolutePath() + "/";
            parametros.put("pathImagen", (Object) abspath);
            parametros.put("barCode", bis);
            //                //Fotografia
            //                ByteArrayInputStream bis = new ByteArrayInputStream(visita.getPersona().getFotografia());
            //                InputStream iS = bis;
            //                parametros.put("fotografia",(Object)iS);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, conexion);

//            //            Muestra el Reporte en Pantalla
//            JasperViewer jviewer = new JasperViewer(jasperPrint, false);
//            jviewer.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
//            jviewer.viewReport(jasperPrint, false);
            
            ///IMPRIMIR DIRECTO A IMPRESORA
            final JRPrintServiceExporter exporter = new JRPrintServiceExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PAGE_DIALOG, Boolean.FALSE);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.FALSE);
            ///BUSCO LA IMPRESORA POR DEFECTO
            PrintServiceAttributeSet printService = new HashPrintServiceAttributeSet();
            PrintService defaultPrinter = PrintServiceLookup.lookupDefaultPrintService();
            printService.add(new PrinterName(defaultPrinter.getName(), Locale.getDefault()));
            ///
            exporter.setParameter(JRPrintServiceExporterParameter.OFFSET_X, new Integer(0));
            exporter.setParameter(JRPrintServiceExporterParameter.OFFSET_Y, new Integer(0));
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE_ATTRIBUTE_SET,printService);
            exporter.exportReport(); 
            
            
            

            //     Genera el Reporte en PDF
            //            JRExporter exporter = new JRPdfExporter();
            //            exporter.setParameter(JRExporterParameter.JASPER_PRINT,jasperPrint);
            //            exporter.setParameter(JRExporterParameter.OUTPUT_FILE,new java.io.File("reportePDF.pdf"));
            //            exporter.exportReport();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(JInternalFramePersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonImprimirVisitaActionPerformed

    private void jButtonBuscarAreaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAreaPersonaActionPerformed
        // TODO add your handling code here:
        JDialogOrganigrama jOrganigrama = new JDialogOrganigrama(null, true);
        jOrganigrama.setModoBuscador(true);
        jOrganigrama.setTitle("Seleccionar Area/Persona Visitada");
        jOrganigrama.setVisible(true);
        jOrganigrama.setResizable(false);
        if (jOrganigrama.getSeleccionado() != null) {
            Object seleccionado = jOrganigrama.getSeleccionado();

            if (seleccionado.getClass().getSimpleName().equals("Persona")) {
                personaVisitada = (Persona) seleccionado;
                organizacionVisitada = null;
                jTextFieldAreaPersonaVisitada.setText(personaVisitada.getApellido() + ", " + personaVisitada.getNombre());
            } else if (seleccionado.getClass().getSimpleName().equals("Organizacion")) {
                personaVisitada = null;
                organizacionVisitada = (Organizacion) seleccionado;
                jTextFieldAreaPersonaVisitada.setText(organizacionVisitada.getNombre());
            }
        }

    }//GEN-LAST:event_jButtonBuscarAreaPersonaActionPerformed

    private void jButtonLimpiarPersonaVisitada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarPersonaVisitada1ActionPerformed
        // TODO add your handling code here:
        personaVisitada = null;
        organizacionVisitada = null;
        jTextFieldAreaPersonaVisitada.setText(null);
    }//GEN-LAST:event_jButtonLimpiarPersonaVisitada1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogConsultaVisitas dialog = new JDialogConsultaVisitas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarAreaPersona;
    private javax.swing.JButton jButtonBuscarOrganizacionExterna;
    private javax.swing.JButton jButtonBuscarPersona;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonImprimirListado;
    private javax.swing.JButton jButtonImprimirVisita;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiarOrganizacion;
    private javax.swing.JButton jButtonLimpiarPersona;
    private javax.swing.JButton jButtonLimpiarPersonaVisitada1;
    private javax.swing.JComboBox jComboBoxMotivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDesde;
    private javax.swing.JFormattedTextField jFormattedTextFieldHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableVisitas;
    private javax.swing.JTextArea jTextAreaObservacion;
    private javax.swing.JTextField jTextFieldAreaPersonaVisitada;
    private javax.swing.JTextField jTextFieldOrganizacionExterna;
    private javax.swing.JTextField jTextFieldPersona;
    private java.util.List listMotivos;
    private java.util.List listOrganizacionInternas;
    private java.util.List listVisitas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
