/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import py.gov.itaipu.controlacceso.view.persona.JInternalFramePersona;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.observablecollections.ObservableCollections;
import py.gov.itaipu.controlacceso.action.CRUDAction;
import py.gov.itaipu.controlacceso.action.persona.PersonaAction;
import py.gov.itaipu.controlacceso.action.visita.VisitaAction;
import py.gov.itaipu.controlacceso.model.Persona;
import py.gov.itaipu.controlacceso.model.TipoDocumento;
import py.gov.itaipu.controlacceso.model.Visita;
import py.gov.itaipu.controlacceso.persistence.EntityManagerCA;
import py.gov.itaipu.controlacceso.utils.windows.WindowUtil;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JDialogOrganigrama;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganigrama;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacionExterna;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameEstado;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameMotivo;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameNacionalidad;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacionInterna;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JDialogTipoDocumento;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameTipoAntecedente;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameTipoDocumento;
import py.gov.itaipu.controlacceso.view.persona.JDialogPersona;
import py.gov.itaipu.controlacceso.view.persona.JDialogPersonaPrincipal;
import py.gov.itaipu.controlacceso.view.reportes.JDialogRepPersonasNoGratas;
import py.gov.itaipu.controlacceso.view.reportes.JDialogRepVisitasAreaPersona;
import py.gov.itaipu.controlacceso.view.reportes.JDialogRepVisitasFecha;
import py.gov.itaipu.controlacceso.view.reportes.JDialogRepVisitasGeneral;
import py.gov.itaipu.controlacceso.view.reportes.JDialogRepVisitasVisitante;
import py.gov.itaipu.controlacceso.view.visita.JDialogConsultaVisitas;
import py.gov.itaipu.controlacceso.view.visita.JDialogVisita;
import py.gov.itaipu.controlacceso.view.visita.JInternalFrameConsultaVisita;
import py.gov.itaipu.controlacceso.view.visita.JInternalFrameRegistroVisita;

/**
 *
 * @author vimartih
 */
public class MDIControlAcceso extends javax.swing.JFrame {

    private VisitaAction visitaAction;
    private PersonaAction personaAction;
    private TableCellRenderer rendererTime;
    private CRUDAction<TipoDocumento> tipoDocAction;
    
    /**
     * Creates new form MDIControlAcceso
     */
    public MDIControlAcceso() {
        visitaAction=new VisitaAction();
        visitaAction.setVisita(new Visita());   
        rendererTime = new TimeRenderer();
        tipoDocAction = new CRUDAction(new TipoDocumento());
        personaAction= new PersonaAction();
        personaAction.setPersona(new Persona());
        initComponents();
        jComboBoxTipoDoc.setVisible(false);
        jLabelTipoDeDoc.setVisible(false);
        jButtonNuevoTipoDoc.setVisible(false);
        jButtonEditTipoDoc.setVisible(false);
        jComboBoxTipoDoc.setSelectedItem(tipoDocAction.findByNamedQuery("TipoDocumento.findCI").get(0));
        this.menuBar.setVisible(false);
        //        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listVisitas = ObservableCollections.observableList(visitaAction.findVisitasPendientes());
        buttonGroupExtranjero = new javax.swing.ButtonGroup();
        listTipoDocumento = ObservableCollections.observableList(tipoDocAction.findAll());
        jPanel1 = new javax.swing.JPanel();
        jLabelDocNro = new javax.swing.JLabel();
        jTextFieldDocumentoPersona = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPersonaVisitada2 = new javax.swing.JLabel();
        jLabelPersonaVisitada1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelDocNro1 = new javax.swing.JLabel();
        jTextFieldNroTicket = new javax.swing.JTextField();
        jLabelPersonaVisitada3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisitas = new javax.swing.JTable();
        jRadioButtonNacional = new javax.swing.JRadioButton();
        jRadioButtonExtranjero = new javax.swing.JRadioButton();
        jLabelTipoDeDoc = new javax.swing.JLabel();
        jComboBoxTipoDoc = new javax.swing.JComboBox();
        jLabelPersonaVisitada4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonVisitantes = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonOrganigrama = new javax.swing.JButton();
        jButtonVisitas = new javax.swing.JButton();
        jLabelPersonaVisitada5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonReporteGeneral = new javax.swing.JButton();
        jButtonReporteVisitasPorVisitante = new javax.swing.JButton();
        jButtonReporteVisitasPorArea = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonReporteVisitasPorPersona1 = new javax.swing.JButton();
        jButtonReporteVisitasPorPersona2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonNuevoTipoDoc = new javax.swing.JButton();
        jButtonEditTipoDoc = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenuPersona = new javax.swing.JMenu();
        jMenuItemRegistro = new javax.swing.JMenuItem();
        jMenuVisita = new javax.swing.JMenu();
        jMenuItemRegistroVisita = new javax.swing.JMenuItem();
        jMenuItemConsultaVisita = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuParametroGeneral = new javax.swing.JMenu();
        jMenuItemMotivoVisita = new javax.swing.JMenuItem();
        jMenuItemEstado = new javax.swing.JMenuItem();
        jMenuItemAntecedente = new javax.swing.JMenuItem();
        jMenuItemTipoDocumento = new javax.swing.JMenuItem();
        jMenuItemNacionalidad = new javax.swing.JMenuItem();
        jMenuOrganizacion = new javax.swing.JMenu();
        jMenuItemOrganizacionInterna = new javax.swing.JMenuItem();
        jMenuItemOrganizacionExterna = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de control de acceso");
        setPreferredSize(new java.awt.Dimension(1275, 621));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelDocNro.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jLabelDocNro.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDocNro.setText("Nro Doc:");

        jTextFieldDocumentoPersona.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jTextFieldDocumentoPersona.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldDocumentoPersona.setToolTipText("Nro de Documento");
        jTextFieldDocumentoPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDocumentoPersonaKeyPressed(evt);
            }
        });

        jLabelPersonaVisitada2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonaVisitada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/handshake48.jpeg"))); // NOI18N
        jLabelPersonaVisitada2.setText("Ingreso.");

        jLabelPersonaVisitada1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonaVisitada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/salida.jpeg"))); // NOI18N
        jLabelPersonaVisitada1.setText("Salida.");

        jLabelDocNro1.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jLabelDocNro1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDocNro1.setText("Nro Ticket:");

        jTextFieldNroTicket.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jTextFieldNroTicket.setForeground(new java.awt.Color(204, 0, 0));
        jTextFieldNroTicket.setToolTipText("El número de ticket generado para la visita.");
        jTextFieldNroTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroTicketActionPerformed(evt);
            }
        });
        jTextFieldNroTicket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNroTicketKeyPressed(evt);
            }
        });

        jLabelPersonaVisitada3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonaVisitada3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/ficha.png"))); // NOI18N
        jLabelPersonaVisitada3.setText("Visitas Activas.");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listVisitas, jTableVisitas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Nro. Ticket");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${persona.nombre} ${persona.apellido}"));
        columnBinding.setColumnName("Persona");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${persona.numeroDocumento}"));
        columnBinding.setColumnName("Nro. Doc");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${motivo.nombre}"));
        columnBinding.setColumnName("Motivo");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaIngreso}"));
        columnBinding.setColumnName("Ingreso");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${personaVisitada.nombre} ${personaVisitada.apellido}"));
        columnBinding.setColumnName("Persona Visitada");
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${organizacionInterna.nombre}"));
        columnBinding.setColumnName("Area Visitada");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableVisitas);
        jTableVisitas.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableVisitas.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableVisitas.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTableVisitas.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTableVisitas.getColumnModel().getColumn(4).setCellRenderer(rendererTime);

        buttonGroupExtranjero.add(jRadioButtonNacional);
        jRadioButtonNacional.setSelected(true);
        jRadioButtonNacional.setText("Paraguayo");
        jRadioButtonNacional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNacionalItemStateChanged(evt);
            }
        });

        buttonGroupExtranjero.add(jRadioButtonExtranjero);
        jRadioButtonExtranjero.setText("Extranjero");
        jRadioButtonExtranjero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonExtranjeroItemStateChanged(evt);
            }
        });

        jLabelTipoDeDoc.setText("Tipo De doc:");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listTipoDocumento, jComboBoxTipoDoc);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxTipoDoc.setSelectedItem(null);

        jLabelPersonaVisitada4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonaVisitada4.setText("Informes");

        jButtonVisitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/ficha.png"))); // NOI18N
        jButtonVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisitantesActionPerformed(evt);
            }
        });

        jButtonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/logo_itaipu.png"))); // NOI18N
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });

        jButtonOrganigrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/organigrama.png"))); // NOI18N
        jButtonOrganigrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrganigramaActionPerformed(evt);
            }
        });

        jButtonVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/handshake48.jpeg"))); // NOI18N
        jButtonVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisitasActionPerformed(evt);
            }
        });

        jLabelPersonaVisitada5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonaVisitada5.setText("Datos del Sistema");

        jLabel1.setText("Visitantes");

        jLabel2.setText("Organigrama");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Visitas");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Acerca de");

        jButtonReporteGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jButtonReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteGeneralActionPerformed(evt);
            }
        });

        jButtonReporteVisitasPorVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jButtonReporteVisitasPorVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteVisitasPorVisitanteActionPerformed(evt);
            }
        });

        jButtonReporteVisitasPorArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jButtonReporteVisitasPorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteVisitasPorAreaActionPerformed(evt);
            }
        });

        jLabel5.setText("General");

        jLabel6.setText("Visitas por Visitante");

        jLabel7.setText("Visitas por Area/Persona");

        jLabel8.setText("Visitas por Rango Fecha");

        jButtonReporteVisitasPorPersona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jButtonReporteVisitasPorPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteVisitasPorPersona1ActionPerformed(evt);
            }
        });

        jButtonReporteVisitasPorPersona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jButtonReporteVisitasPorPersona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteVisitasPorPersona2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Personas no Gratas");

        jButtonNuevoTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/new.jpg"))); // NOI18N
        jButtonNuevoTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTipoDocActionPerformed(evt);
            }
        });

        jButtonEditTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/edit.png"))); // NOI18N
        jButtonEditTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTipoDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPersonaVisitada2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonNacional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonExtranjero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTipoDeDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPersonaVisitada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDocNro1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNroTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDocumentoPersona)))
                            .addComponent(jLabelDocNro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonOrganigrama, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelPersonaVisitada4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaVisitada5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonReporteVisitasPorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonReporteGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonReporteVisitasPorVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonReporteVisitasPorPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonReporteVisitasPorPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPersonaVisitada3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPersonaVisitada3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelPersonaVisitada2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDocNro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDocumentoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonNacional)
                                .addComponent(jRadioButtonExtranjero)
                                .addComponent(jLabelTipoDeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabelPersonaVisitada1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDocNro1)
                            .addComponent(jTextFieldNroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelPersonaVisitada5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonVisitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonVisitantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonOrganigrama, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPersonaVisitada4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonReporteGeneral, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonReporteVisitasPorPersona1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonReporteVisitasPorVisitante, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jButtonReporteVisitasPorPersona2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonReporteVisitasPorArea)
                            .addComponent(jLabel7))
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldDocumentoPersona, jTextFieldNroTicket});

        jMenuPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Boss.gif"))); // NOI18N
        jMenuPersona.setText("Persona");

        jMenuItemRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Boss.gif"))); // NOI18N
        jMenuItemRegistro.setText("Registro de Personas");
        jMenuItemRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroActionPerformed(evt);
            }
        });
        jMenuPersona.add(jMenuItemRegistro);

        menuBar.add(jMenuPersona);

        jMenuVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-clock.png"))); // NOI18N
        jMenuVisita.setText("Visita");

        jMenuItemRegistroVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-clock.png"))); // NOI18N
        jMenuItemRegistroVisita.setText("Registro de visitas");
        jMenuItemRegistroVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroVisitaActionPerformed(evt);
            }
        });
        jMenuVisita.add(jMenuItemRegistroVisita);

        jMenuItemConsultaVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jMenuItemConsultaVisita.setText("Consulta de visitas");
        jMenuItemConsultaVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaVisitaActionPerformed(evt);
            }
        });
        jMenuVisita.add(jMenuItemConsultaVisita);

        menuBar.add(jMenuVisita);

        jMenuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/manage_icon.png"))); // NOI18N
        jMenuAdministracion.setText("Administración");

        jMenuParametroGeneral.setText("Parametros Generales");

        jMenuItemMotivoVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/handshake.jpg"))); // NOI18N
        jMenuItemMotivoVisita.setText("Motivo Visita");
        jMenuItemMotivoVisita.setPreferredSize(new java.awt.Dimension(24, 22));
        jMenuItemMotivoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotivoVisitaActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemMotivoVisita);

        jMenuItemEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Alert.gif"))); // NOI18N
        jMenuItemEstado.setText("Estado Persona");
        jMenuItemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemEstado);

        jMenuItemAntecedente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/tipoAntecente.gif"))); // NOI18N
        jMenuItemAntecedente.setText("Tipo Antecedente");
        jMenuItemAntecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAntecedenteActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemAntecedente);

        jMenuItemTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jMenuItemTipoDocumento.setText("Tipo Documento");
        jMenuItemTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoDocumentoActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemTipoDocumento);

        jMenuItemNacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/mundo.png"))); // NOI18N
        jMenuItemNacionalidad.setText("Nacionalidad");
        jMenuItemNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNacionalidadActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemNacionalidad);

        jMenuAdministracion.add(jMenuParametroGeneral);

        jMenuOrganizacion.setText("Organizacion");

        jMenuItemOrganizacionInterna.setText("Organizacion Interna");
        jMenuItemOrganizacionInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrganizacionInternaActionPerformed(evt);
            }
        });
        jMenuOrganizacion.add(jMenuItemOrganizacionInterna);

        jMenuItemOrganizacionExterna.setText("Organizacion Externa");
        jMenuItemOrganizacionExterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrganizacionExternaActionPerformed(evt);
            }
        });
        jMenuOrganizacion.add(jMenuItemOrganizacionExterna);

        jMenuAdministracion.add(jMenuOrganizacion);

        menuBar.add(jMenuAdministracion);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/help.jpeg"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMotivoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotivoVisitaActionPerformed
        // TODO add your handling code here:
        JInternalFrameMotivo motivoFrame = new JInternalFrameMotivo();
        motivoFrame.setVisible(true);
//        this.desktopPane.add(motivoFrame);
    }//GEN-LAST:event_jMenuItemMotivoVisitaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        EntityManagerCA.cerrar();
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoActionPerformed
        // TODO add your handling code here:
        JInternalFrameEstado estadoFrame = new JInternalFrameEstado();
        estadoFrame.setVisible(true);
//        this.desktopPane.add(estadoFrame);
    }//GEN-LAST:event_jMenuItemEstadoActionPerformed

    private void jMenuItemAntecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAntecedenteActionPerformed
        // TODO add your handling code here:
        JInternalFrameTipoAntecedente tipoAntecedenteFrame = new JInternalFrameTipoAntecedente();
        tipoAntecedenteFrame.setVisible(true);
//        this.desktopPane.add(tipoAntecedenteFrame);
    }//GEN-LAST:event_jMenuItemAntecedenteActionPerformed

    private void jMenuItemTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoDocumentoActionPerformed
        // TODO add your handling code here:
        JInternalFrameTipoDocumento tipoDocumentoFrame = new JInternalFrameTipoDocumento();
        tipoDocumentoFrame.setVisible(true);
//        this.desktopPane.add(tipoDocumentoFrame);
    }//GEN-LAST:event_jMenuItemTipoDocumentoActionPerformed

    private void jMenuItemNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNacionalidadActionPerformed
        // TODO add your handling code here:
        JInternalFrameNacionalidad nacionalidadFrame = new JInternalFrameNacionalidad();
        nacionalidadFrame.setVisible(true);
//        this.desktopPane.add(nacionalidadFrame);
    }//GEN-LAST:event_jMenuItemNacionalidadActionPerformed

    private void jMenuItemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroActionPerformed
        // TODO add your handling code here:
//        JInternalFramePersona personaFrame = new JInternalFramePersona();
//        personaFrame.setVisible(true);
//        this.desktopPane.add(personaFrame);
//        
        JDialogPersonaPrincipal dialogPersona = new JDialogPersonaPrincipal(null, false);
        dialogPersona.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemRegistroActionPerformed

    private void jMenuItemOrganizacionInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrganizacionInternaActionPerformed
        // TODO add your handling code here:
//        JInternalFrameOrganizacionInterna organizacionInternaFrame = new JInternalFrameOrganizacionInterna();
        JInternalFrameOrganigrama organizacionInternaFrame = new JInternalFrameOrganigrama();
        organizacionInternaFrame.setVisible(true);
//        this.desktopPane.add(organizacionInternaFrame);
    }//GEN-LAST:event_jMenuItemOrganizacionInternaActionPerformed

    private void jMenuItemOrganizacionExternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrganizacionExternaActionPerformed
        // TODO add your handling code here:
        JInternalFrameOrganizacionExterna organizacionExternaFrame = new JInternalFrameOrganizacionExterna();
        organizacionExternaFrame.setVisible(true);
//        this.desktopPane.add(organizacionExternaFrame);
    }//GEN-LAST:event_jMenuItemOrganizacionExternaActionPerformed

    private void jMenuItemRegistroVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroVisitaActionPerformed
        // TODO add your handling code here:
        JInternalFrameRegistroVisita registroVisitaFrame = new JInternalFrameRegistroVisita();
        registroVisitaFrame.setVisible(true);
//        this.desktopPane.add(registroVisitaFrame);
    }//GEN-LAST:event_jMenuItemRegistroVisitaActionPerformed

    private void jMenuItemConsultaVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaVisitaActionPerformed
        // TODO add your handling code here:
        JInternalFrameConsultaVisita consultaVisitaFrame = new JInternalFrameConsultaVisita();
        consultaVisitaFrame.setVisible(true);
//        this.desktopPane.add(consultaVisitaFrame);
    }//GEN-LAST:event_jMenuItemConsultaVisitaActionPerformed

    private void jTextFieldNroTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNroTicketActionPerformed

    private void jTextFieldNroTicketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNroTicketKeyPressed
        // TODO add your handling code here:       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldNroTicket.getText() != null && !jTextFieldNroTicket.getText().equals("")) {
                Visita v = visitaAction.findPendienteById(Long.parseLong(jTextFieldNroTicket.getText()));
                if(v==null){
                    JOptionPane.showMessageDialog(this, "No existe la visita.", "Error", 0);
                    return;
                }
                Calendar c = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
                if (JOptionPane.showConfirmDialog(this, "Está seguro que desea marcar la salida de "
                        + v.getPersona().getNombre()
                        + " " + v.getPersona().getApellido()
                        + ", a las: " + sdf.format(c.getTime())
                        + "?", "Registro de salida", 0) != 0) {
                    return;
                }

                v.setFechaSalida(c.getTime());
                visitaAction.setVisita(v);
                visitaAction.guardar();
                listVisitas.clear();
                listVisitas.addAll(visitaAction.findVisitasPendientes());
                JOptionPane.showMessageDialog(this, "Se ha registrado la salida correctamente", "Info", 1);
                jTextFieldNroTicket.setText(null);
            }
        }
    }//GEN-LAST:event_jTextFieldNroTicketKeyPressed

    private void jTextFieldDocumentoPersonaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDocumentoPersonaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && jTextFieldDocumentoPersona.getText()!=null && !jTextFieldDocumentoPersona.getText().equals("")) {
            // Enter was pressed. Your code goes here.
            JDialogVisita dialogVisita = new JDialogVisita(this, rootPaneCheckingEnabled);
            WindowUtil.centerWindow(dialogVisita);
            dialogVisita.setVisita(new Visita());
            
            
            if(personaAction.findByNumeroDocumento(jTextFieldDocumentoPersona.getText(),(TipoDocumento) jComboBoxTipoDoc.getSelectedItem()).size()<1){
                if (JOptionPane.showConfirmDialog(this, "La persona no existe, desea registrarla?", "Persona no registrada", 0) != 0) {
                    return;
                }
                JDialogPersona dialogPersona = new JDialogPersona(null, rootPaneCheckingEnabled);
                dialogPersona.getjTextFieldNroDoc().setText(jTextFieldDocumentoPersona.getText());
                dialogPersona.getjTextFieldNroDoc().setEditable(false);
                dialogPersona.getjComboBoxTipoDocumento().setSelectedItem(jComboBoxTipoDoc.getSelectedItem());
                dialogPersona.getjComboBoxTipoDocumento().setEnabled(false);
                WindowUtil.centerWindow(dialogPersona);
                dialogPersona.setVisible(true);
                listTipoDocumento.clear();
                listTipoDocumento.addAll(tipoDocAction.findAll());
                jComboBoxTipoDoc.setSelectedItem(dialogPersona.getjComboBoxTipoDocumento().getSelectedItem());
            }
            
            dialogVisita.getjTextFieldDocumentoPersona().setText(jTextFieldDocumentoPersona.getText());
            dialogVisita.getjComboBoxTipoDoc().setSelectedItem(jComboBoxTipoDoc.getSelectedItem());
            dialogVisita.actualizarDatos();
            if(dialogVisita.getPersona().getId()!=null)
                dialogVisita.setVisible(true);
            listVisitas.clear();
            listVisitas.addAll(visitaAction.findVisitasPendientes());
        }
    }//GEN-LAST:event_jTextFieldDocumentoPersonaKeyPressed

    private void jRadioButtonExtranjeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonExtranjeroItemStateChanged
        // TODO add your handling code here:  
        jComboBoxTipoDoc.setVisible(true);
        jLabelTipoDeDoc.setVisible(true);
        jButtonEditTipoDoc.setVisible(true);
        jButtonNuevoTipoDoc.setVisible(true);
    }//GEN-LAST:event_jRadioButtonExtranjeroItemStateChanged

    private void jRadioButtonNacionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNacionalItemStateChanged
        // TODO add your handling code here:
        jComboBoxTipoDoc.setVisible(false);
        jLabelTipoDeDoc.setVisible(false);
        jButtonEditTipoDoc.setVisible(false);
        jButtonNuevoTipoDoc.setVisible(false);
        jComboBoxTipoDoc.setSelectedItem(tipoDocAction.findByNamedQuery("TipoDocumento.findCI").get(0));
    }//GEN-LAST:event_jRadioButtonNacionalItemStateChanged

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
        JDialogAbout about = new JDialogAbout(this, rootPaneCheckingEnabled);
        WindowUtil.centerWindow(about);
        about.setVisible(true);
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisitasActionPerformed
        // TODO add your handling code here:
        JDialogConsultaVisitas visitas = new JDialogConsultaVisitas(this, rootPaneCheckingEnabled);
        WindowUtil.centerWindow(visitas);
        visitas.setVisible(true);
        
    }//GEN-LAST:event_jButtonVisitasActionPerformed

    private void jButtonVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisitantesActionPerformed
        // TODO add your handling code here:
        JDialogPersonaPrincipal dialogPersona = new JDialogPersonaPrincipal(null, false);
        WindowUtil.centerWindow(dialogPersona);
        dialogPersona.setVisible(true);
    }//GEN-LAST:event_jButtonVisitantesActionPerformed

    private void jButtonOrganigramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrganigramaActionPerformed
        // TODO add your handling code here:
        JDialogOrganigrama dialogOrganigrama = new JDialogOrganigrama(null, false);
        WindowUtil.centerWindow(dialogOrganigrama);
        dialogOrganigrama.setVisible(true);
    }//GEN-LAST:event_jButtonOrganigramaActionPerformed

    private void jButtonReporteVisitasPorPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteVisitasPorPersona1ActionPerformed
        // TODO add your handling code here:
        JDialogRepVisitasFecha dialogRepVisFec = new JDialogRepVisitasFecha(null, false);
        WindowUtil.centerWindow(dialogRepVisFec);
        dialogRepVisFec.setVisible(true);
    }//GEN-LAST:event_jButtonReporteVisitasPorPersona1ActionPerformed

    private void jButtonReporteVisitasPorVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteVisitasPorVisitanteActionPerformed
        // TODO add your handling code here:
        JDialogRepVisitasVisitante dialogRepVisVis = new JDialogRepVisitasVisitante(null, false);
        WindowUtil.centerWindow(dialogRepVisVis);
        dialogRepVisVis.setVisible(true);
    }//GEN-LAST:event_jButtonReporteVisitasPorVisitanteActionPerformed

    private void jButtonReporteVisitasPorAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteVisitasPorAreaActionPerformed
        // TODO add your handling code here:
        JDialogRepVisitasAreaPersona dialogRepVisAreaPers = new JDialogRepVisitasAreaPersona(null, false);
        WindowUtil.centerWindow(dialogRepVisAreaPers);
        dialogRepVisAreaPers.setVisible(true);
    }//GEN-LAST:event_jButtonReporteVisitasPorAreaActionPerformed

    private void jButtonReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteGeneralActionPerformed
        // TODO add your handling code here:
        JDialogRepVisitasGeneral dialogRepVisGen = new JDialogRepVisitasGeneral(null, false);
        WindowUtil.centerWindow(dialogRepVisGen);
        dialogRepVisGen.setVisible(true);
    }//GEN-LAST:event_jButtonReporteGeneralActionPerformed

    private void jButtonReporteVisitasPorPersona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteVisitasPorPersona2ActionPerformed
        // TODO add your handling code here:
        JDialogRepPersonasNoGratas dialogRepPersNoGratas = new JDialogRepPersonasNoGratas(null, false);
        WindowUtil.centerWindow(dialogRepPersNoGratas);
        dialogRepPersNoGratas.setVisible(true);
    }//GEN-LAST:event_jButtonReporteVisitasPorPersona2ActionPerformed

    private void jButtonNuevoTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTipoDocActionPerformed
        // TODO add your handling code here:
        TipoDocumento td = (TipoDocumento) jComboBoxTipoDoc.getSelectedItem();
        JDialogTipoDocumento dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
        dialogTipoDocumento.setTipoDocumento(new TipoDocumento());
        WindowUtil.centerWindow(dialogTipoDocumento);
        dialogTipoDocumento.setVisible(true);
        listTipoDocumento.clear();
        listTipoDocumento.addAll(tipoDocAction.findAll());
        if (dialogTipoDocumento.getTipoDocumento().getId()!=null) {
            jComboBoxTipoDoc.setSelectedItem(dialogTipoDocumento.getTipoDocumento());
        }else{
            jComboBoxTipoDoc.setSelectedItem(td);
        }
    }//GEN-LAST:event_jButtonNuevoTipoDocActionPerformed

    private void jButtonEditTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTipoDocActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JDialogTipoDocumento dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
        dialogTipoDocumento.setTipoDocumento((TipoDocumento)jComboBoxTipoDoc.getSelectedItem());
        WindowUtil.centerWindow(dialogTipoDocumento);
        dialogTipoDocumento.setVisible(true);
        listTipoDocumento.clear();
        listTipoDocumento.addAll(tipoDocAction.findAll());
        jComboBoxTipoDoc.setSelectedItem(dialogTipoDocumento.getTipoDocumento());
    }//GEN-LAST:event_jButtonEditTipoDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIControlAcceso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroupExtranjero;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButtonEditTipoDoc;
    private javax.swing.JButton jButtonNuevoTipoDoc;
    private javax.swing.JButton jButtonOrganigrama;
    private javax.swing.JButton jButtonReporteGeneral;
    private javax.swing.JButton jButtonReporteVisitasPorArea;
    private javax.swing.JButton jButtonReporteVisitasPorPersona1;
    private javax.swing.JButton jButtonReporteVisitasPorPersona2;
    private javax.swing.JButton jButtonReporteVisitasPorVisitante;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonVisitantes;
    private javax.swing.JButton jButtonVisitas;
    private javax.swing.JComboBox jComboBoxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDocNro;
    private javax.swing.JLabel jLabelDocNro1;
    private javax.swing.JLabel jLabelPersonaVisitada1;
    private javax.swing.JLabel jLabelPersonaVisitada2;
    private javax.swing.JLabel jLabelPersonaVisitada3;
    private javax.swing.JLabel jLabelPersonaVisitada4;
    private javax.swing.JLabel jLabelPersonaVisitada5;
    private javax.swing.JLabel jLabelTipoDeDoc;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenuItem jMenuItemAntecedente;
    private javax.swing.JMenuItem jMenuItemConsultaVisita;
    private javax.swing.JMenuItem jMenuItemEstado;
    private javax.swing.JMenuItem jMenuItemMotivoVisita;
    private javax.swing.JMenuItem jMenuItemNacionalidad;
    private javax.swing.JMenuItem jMenuItemOrganizacionExterna;
    private javax.swing.JMenuItem jMenuItemOrganizacionInterna;
    private javax.swing.JMenuItem jMenuItemRegistro;
    private javax.swing.JMenuItem jMenuItemRegistroVisita;
    private javax.swing.JMenuItem jMenuItemTipoDocumento;
    private javax.swing.JMenu jMenuOrganizacion;
    private javax.swing.JMenu jMenuParametroGeneral;
    private javax.swing.JMenu jMenuPersona;
    private javax.swing.JMenu jMenuVisita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonExtranjero;
    private javax.swing.JRadioButton jRadioButtonNacional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTableVisitas;
    private javax.swing.JTextField jTextFieldDocumentoPersona;
    private javax.swing.JTextField jTextFieldNroTicket;
    private java.util.List listTipoDocumento;
    private java.util.List listVisitas;
    private javax.swing.JMenuBar menuBar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
