/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view;


import javax.persistence.EntityManager;
import py.gov.itaipu.controlacceso.persistence.EntityManagerCA;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameEstado;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameMotivo;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameTipoAntecedente;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JInternalFrameTipoDocumento;

/**
 *
 * @author vimartih
 */
public class MDIControlAcceso extends javax.swing.JFrame {

    /**
     * Creates new form MDIControlAcceso
     */
    
    
    public MDIControlAcceso() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenuPersona = new javax.swing.JMenu();
        jMenuItemPersonaNueva = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuParametroGeneral = new javax.swing.JMenu();
        jMenuItemMotivoVisita = new javax.swing.JMenuItem();
        jMenuItemEstado = new javax.swing.JMenuItem();
        jMenuItemAntecedente = new javax.swing.JMenuItem();
        jMenuItemTipoDocumento = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de control de acceso");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenuPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Boss.gif"))); // NOI18N
        jMenuPersona.setText("Persona");

        jMenuItemPersonaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/edit.png"))); // NOI18N
        jMenuItemPersonaNueva.setText("Nueva");
        jMenuItemPersonaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPersonaNuevaActionPerformed(evt);
            }
        });
        jMenuPersona.add(jMenuItemPersonaNueva);

        menuBar.add(jMenuPersona);

        jMenuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/manage_icon.png"))); // NOI18N
        jMenuAdministracion.setText("Administración");

        jMenuParametroGeneral.setText("Parametros Generales");

        jMenuItemMotivoVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/handshake.jpg"))); // NOI18N
        jMenuItemMotivoVisita.setText("Motivo Visita");
        jMenuItemMotivoVisita.setPreferredSize(new java.awt.Dimension(24, 22));
        jMenuItemMotivoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotivoVisitaActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemMotivoVisita);

        jMenuItemEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Alert.gif"))); // NOI18N
        jMenuItemEstado.setText("Estado Persona");
        jMenuItemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemEstado);

        jMenuItemAntecedente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/tipoAntecente.gif"))); // NOI18N
        jMenuItemAntecedente.setText("Tipo Antecedente");
        jMenuItemAntecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAntecedenteActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemAntecedente);

        jMenuItemTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/icon-doc.gif"))); // NOI18N
        jMenuItemTipoDocumento.setText("Tipo Documento");
        jMenuItemTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoDocumentoActionPerformed(evt);
            }
        });
        jMenuParametroGeneral.add(jMenuItemTipoDocumento);

        jMenuAdministracion.add(jMenuParametroGeneral);

        menuBar.add(jMenuAdministracion);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/help.jpeg"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPersonaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPersonaNuevaActionPerformed
        // TODO add your handling code here:           
        JInternalFramePersona personaFrame=new JInternalFramePersona();
        personaFrame.setVisible(true);
        this.desktopPane.add(personaFrame);
    }//GEN-LAST:event_jMenuItemPersonaNuevaActionPerformed

    private void jMenuItemMotivoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotivoVisitaActionPerformed
        // TODO add your handling code here:
        JInternalFrameMotivo motivoFrame=new JInternalFrameMotivo();
        motivoFrame.setVisible(true);
        this.desktopPane.add(motivoFrame);
    }//GEN-LAST:event_jMenuItemMotivoVisitaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        EntityManagerCA.cerrar();
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoActionPerformed
        // TODO add your handling code here:
        JInternalFrameEstado estadoFrame=new JInternalFrameEstado();
        estadoFrame.setVisible(true);
        this.desktopPane.add(estadoFrame);
    }//GEN-LAST:event_jMenuItemEstadoActionPerformed

    private void jMenuItemAntecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAntecedenteActionPerformed
        // TODO add your handling code here:
        JInternalFrameTipoAntecedente tipoAntecedenteFrame=new JInternalFrameTipoAntecedente();
        tipoAntecedenteFrame.setVisible(true);
        this.desktopPane.add(tipoAntecedenteFrame);
    }//GEN-LAST:event_jMenuItemAntecedenteActionPerformed

    private void jMenuItemTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoDocumentoActionPerformed
        // TODO add your handling code here:
        JInternalFrameTipoDocumento tipoDocumentoFrame=new JInternalFrameTipoDocumento();
        tipoDocumentoFrame.setVisible(true);
        this.desktopPane.add(tipoDocumentoFrame);
    }//GEN-LAST:event_jMenuItemTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIControlAcceso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenuItem jMenuItemAntecedente;
    private javax.swing.JMenuItem jMenuItemEstado;
    private javax.swing.JMenuItem jMenuItemMotivoVisita;
    private javax.swing.JMenuItem jMenuItemPersonaNueva;
    private javax.swing.JMenuItem jMenuItemTipoDocumento;
    private javax.swing.JMenu jMenuParametroGeneral;
    private javax.swing.JMenu jMenuPersona;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
