/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.gov.itaipu.controlacceso.view.persona;

import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStreamImpl;
import javax.imageio.stream.ImageOutputStreamImpl;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import py.gov.itaipu.controlacceso.action.CRUDAction;
import py.gov.itaipu.controlacceso.model.Nacionalidad;
import py.gov.itaipu.controlacceso.model.TipoDocumento;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JDialogTipoDocumento;
import org.jdesktop.observablecollections.ObservableCollections;
import py.gov.itaipu.controlacceso.action.persona.PersonaAction;
import py.gov.itaipu.controlacceso.model.Antecedente;
import py.gov.itaipu.controlacceso.model.Organizacion;
import py.gov.itaipu.controlacceso.model.Persona;
import py.gov.itaipu.controlacceso.test.ImageFrame;
import py.gov.itaipu.controlacceso.test.ShowImage;
import py.gov.itaipu.controlacceso.view.JDialogBuscador;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacion;
import py.gov.itaipu.controlacceso.view.administracion.organizacion.JInternalFrameOrganizacionExterna;
import py.gov.itaipu.controlacceso.view.administracion.parametrogeneral.JDialogoNacionalidad;

/**
 *
 * @author fboy
 */
public class JDialogPersona extends javax.swing.JDialog {

    private CRUDAction<Nacionalidad> nacionalidadAction;
    private CRUDAction<TipoDocumento> tipoDocAction;
    private CRUDAction<Organizacion> organizacionAction;
    private CRUDAction<Antecedente> antecedenteAction;
    private PersonaAction personaAction;
    private Persona persona;
    private Boolean readOnly;
    private BufferedImage imagePersona;
    private ImageIcon iconoFoto;

    /**
     * Creates new form JDialogPersona
     */
    public JDialogPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        readOnly = false;
        persona = new Persona();
        persona.setAntecedentes(new ArrayList<Antecedente>());
        personaAction = new PersonaAction(persona);
        nacionalidadAction = new CRUDAction(new Nacionalidad());
        tipoDocAction = new CRUDAction(new TipoDocumento());
        organizacionAction = new CRUDAction(new Organizacion());
        antecedenteAction = new CRUDAction(new Antecedente());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listNacionalidades = nacionalidadAction.findAll();
        listTipoDocumento = ObservableCollections.observableList(tipoDocAction.findAll());
        listOrganizaciones = ObservableCollections.observableList(organizacionAction.findAll());
        listAntecedentes = ObservableCollections.observableList(persona.getAntecedentes())
        ;
        jTabbedPanePersona = new javax.swing.JTabbedPane();
        jPanelDatosPersonales = new javax.swing.JPanel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApe = new javax.swing.JLabel();
        jLabelNomb = new javax.swing.JLabel();
        jLabelNroD = new javax.swing.JLabel();
        jLabelTipDoc = new javax.swing.JLabel();
        jLabelNAcion = new javax.swing.JLabel();
        jLabelEstCiv = new javax.swing.JLabel();
        jTextFieldNroDoc = new javax.swing.JTextField();
        jComboBoxTipoDocumento = new javax.swing.JComboBox();
        jComboBoxNacionalidad = new javax.swing.JComboBox();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jButtonNuevoTipoDoc = new javax.swing.JButton();
        jButtonNuevoNacionalidad = new javax.swing.JButton();
        jLabelFechaNac = new javax.swing.JLabel();
        jFormattedTextFieldFechaNac = new javax.swing.JFormattedTextField();
        jPanelFotografia = new javax.swing.JPanel()
        ;
        jLabel3 = new javax.swing.JLabel();
        jButtonCargarFoto = new javax.swing.JButton();
        jPanelOrganizacion = new javax.swing.JPanel();
        jLabelOrganizacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelOrgDes = new javax.swing.JLabel();
        jLabelOrgTelef = new javax.swing.JLabel();
        jLabelOrgDirec = new javax.swing.JLabel();
        jLabelOrgCont = new javax.swing.JLabel();
        jTextFieldOrgDesc = new javax.swing.JTextField();
        jTextFieldOrgTelef = new javax.swing.JTextField();
        jTextFieldOrgDir = new javax.swing.JTextField();
        jTextFieldOrgContac = new javax.swing.JTextField();
        jLabelOrganizacion1 = new javax.swing.JLabel();
        jTextFieldOrganizacion = new javax.swing.JTextField();
        jButtonBuscarOrganizacion = new javax.swing.JButton();
        jPanelAntecedentes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Personas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                JDialogPersona.this.windowActivated(evt);
            }
        });

        jLabelApe.setText("Apellido");

        jLabelNomb.setText("Nombre");

        jLabelNroD.setText("Nro Documento");

        jLabelTipDoc.setText("Tipo Documento");

        jLabelNAcion.setText("Nacionalidad");

        jLabelEstCiv.setText("Estado Civil");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listTipoDocumento, jComboBoxTipoDocumento);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listNacionalidades, jComboBoxNacionalidad);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO" }));

        jButtonNuevoTipoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/new.jpg"))); // NOI18N
        jButtonNuevoTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTipoDocActionPerformed(evt);
            }
        });

        jButtonNuevoNacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/new.jpg"))); // NOI18N
        jButtonNuevoNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoNacionalidadActionPerformed(evt);
            }
        });

        jLabelFechaNac.setText("Fecha de Nacimiento");

        jFormattedTextFieldFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApe)
                            .addComponent(jLabelNomb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabelNroD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstCiv)
                            .addComponent(jLabelNAcion)
                            .addComponent(jLabelTipDoc)
                            .addComponent(jLabelFechaNac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldFechaNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(165, 165, 165))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabelTipDoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelApe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNroD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNuevoTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNAcion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonNuevoNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstCiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNac))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPanePersona.addTab("Datos Personales", jPanelDatosPersonales);

        iconoFoto = new javax.swing.ImageIcon(getClass().getResource("/resource/img/sin_foto.jpg"));
        jLabel3.setIcon(iconoFoto);

        jButtonCargarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/Boss.gif"))); // NOI18N
        jButtonCargarFoto.setText("Cargar Fotografia");
        jButtonCargarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFotografiaLayout = new javax.swing.GroupLayout(jPanelFotografia);
        jPanelFotografia.setLayout(jPanelFotografiaLayout);
        jPanelFotografiaLayout.setHorizontalGroup(
            jPanelFotografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFotografiaLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(jPanelFotografiaLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButtonCargarFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFotografiaLayout.setVerticalGroup(
            jPanelFotografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFotografiaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCargarFoto)
                .addContainerGap())
        );

        jTabbedPanePersona.addTab("Fotografia", jPanelFotografia);

        jLabelOrganizacion.setText("Organizacion");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));

        jLabelOrgDes.setText("Descripcion");

        jLabelOrgTelef.setText("Teléfono");

        jLabelOrgDirec.setText("Direccion");

        jLabelOrgCont.setText("Contacto");

        jTextFieldOrgDesc.setEditable(false);
        jTextFieldOrgDesc.setText("Descripcion de Muestra");

        jTextFieldOrgTelef.setEditable(false);
        jTextFieldOrgTelef.setText("Teléfono de Muestra");

        jTextFieldOrgDir.setEditable(false);
        jTextFieldOrgDir.setText("Direccion de Muestra");

        jTextFieldOrgContac.setEditable(false);
        jTextFieldOrgContac.setText("Contacto de Muestra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOrgDirec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOrgCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOrgTelef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOrgDes, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldOrgDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jTextFieldOrgTelef)
                    .addComponent(jTextFieldOrgDir)
                    .addComponent(jTextFieldOrgContac)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrgDes)
                    .addComponent(jTextFieldOrgDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrgTelef)
                    .addComponent(jTextFieldOrgTelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrgDirec)
                    .addComponent(jTextFieldOrgDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrgCont)
                    .addComponent(jTextFieldOrgContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabelOrganizacion1.setText("Datos Organizacion Externa");

        jTextFieldOrganizacion.setEditable(false);

        jButtonBuscarOrganizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/view.png"))); // NOI18N
        jButtonBuscarOrganizacion.setToolTipText("Buscar Organizacion");
        jButtonBuscarOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarOrganizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrganizacionLayout = new javax.swing.GroupLayout(jPanelOrganizacion);
        jPanelOrganizacion.setLayout(jPanelOrganizacionLayout);
        jPanelOrganizacionLayout.setHorizontalGroup(
            jPanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrganizacionLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelOrganizacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelOrganizacionLayout.createSequentialGroup()
                        .addComponent(jLabelOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanelOrganizacionLayout.setVerticalGroup(
            jPanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrganizacionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanelOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrganizacion)
                    .addComponent(jTextFieldOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabelOrganizacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPanePersona.addTab("Organizacion", jPanelOrganizacion);

        jLabel2.setText("Tiene Antecedentes?");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listAntecedentes, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoAntecedente.nombre}"));
        columnBinding.setColumnName("Tipo Antecedente");
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${observacion}"));
        columnBinding.setColumnName("Observacion");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelAntecedentesLayout = new javax.swing.GroupLayout(jPanelAntecedentes);
        jPanelAntecedentes.setLayout(jPanelAntecedentesLayout);
        jPanelAntecedentesLayout.setHorizontalGroup(
            jPanelAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntecedentesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelAntecedentesLayout.setVerticalGroup(
            jPanelAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntecedentesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPanePersona.addTab("Antecedentes", jPanelAntecedentes);

        jLabel1.setText("Datos Persona");

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/save.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/exit.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1)
                    .addComponent(jTabbedPanePersona))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTipoDocActionPerformed
        // TODO add your handling code here:
        JDialogTipoDocumento dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
        dialogTipoDocumento.setTipoDocumento(new TipoDocumento());
        dialogTipoDocumento.setVisible(true);
        listTipoDocumento.clear();
        listTipoDocumento.addAll(tipoDocAction.findAll());
    }//GEN-LAST:event_jButtonNuevoTipoDocActionPerformed

    public void cargarDatospersona() {
        jTextFieldApellido.setText(persona.getApellido().toUpperCase());
        jTextFieldNombre.setText(persona.getNombre().toUpperCase());
        jTextFieldNroDoc.setText(persona.getNumeroDocumento().toUpperCase());
        jTextFieldOrganizacion.setText((persona.getOrganizacion().getNombre()));
        jFormattedTextFieldFechaNac.setValue(persona.getFechaNacimiento());
        jComboBoxEstadoCivil.setSelectedItem(persona.getEstadoCivil().toUpperCase());
        jComboBoxNacionalidad.setSelectedItem(persona.getNacionalidad());
        jComboBoxTipoDocumento.setSelectedItem(persona.getTipoDocumento());

        //Cargar Fotografia
        if (persona.getFotografia() != null) {
            ByteArrayInputStream bis = new ByteArrayInputStream(persona.getFotografia());
            BufferedImage image;
            try {
                image = ImageIO.read(bis);
                iconoFoto = new javax.swing.ImageIcon(image);
                jLabel3.setIcon(iconoFoto);
            } catch (IOException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            }

            listAntecedentes.clear();
            if (persona.getAntecedentes() != null) {
                listAntecedentes.addAll(persona.getAntecedentes());
            }
        }



    }

    public Persona getPersona() {
        return persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Boolean getReadOnly() {
        return readOnly;
    }

    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }

    private void jButtonNuevoNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoNacionalidadActionPerformed
        // TODO add your handling code here:
//        JDialogoNacionalidad dialogTipoDocumento = new JDialogTipoDocumento(null, rootPaneCheckingEnabled);
//        dialogTipoDocumento.setTipoDocumento(new TipoDocumento());
//        dialogTipoDocumento.setVisible(true);
//        listTipoDocumento.clear();
//        listTipoDocumento.addAll(tipoDocAction.findAll());
    }//GEN-LAST:event_jButtonNuevoNacionalidadActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (validacionesNuevaPersona()) {
            personaAction.setPersona(persona);
            persona.setApellido(jTextFieldApellido.getText());
            persona.setNombre(jTextFieldNombre.getText());
            persona.setNumeroDocumento(jTextFieldNroDoc.getText());
            persona.setFechaNacimiento((Date) jFormattedTextFieldFechaNac.getValue());
            persona.setEstadoCivil(jComboBoxEstadoCivil.getSelectedItem().toString());
            persona.setNacionalidad((Nacionalidad) listNacionalidades.get(jComboBoxNacionalidad.getSelectedIndex()));
            persona.setTipoDocumento((TipoDocumento) listTipoDocumento.get(jComboBoxTipoDocumento.getSelectedIndex()));

            if (persona.getId() != null) {
                personaAction.guardar();
                JOptionPane.showMessageDialog(this, "Se ha guardado con exito los nuevos Datos de Persona", "Info", 1);
            } else {
                personaAction.crear();
                JOptionPane.showMessageDialog(this, "Se ha creado con exito nueva Persona", "Info", 1);
            }
            this.dispose();
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private boolean validacionesNuevaPersona() {
        boolean resultado = true;
        if (jTextFieldApellido.getText() == null || jTextFieldApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Apellido es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jTextFieldNombre.getText() == null || jTextFieldNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nombre es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jTextFieldNroDoc.getText() == null || jTextFieldNroDoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nro Documento es Obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (jComboBoxTipoDocumento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Seleccionar el Tipo de Documento", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        } else if (persona.getOrganizacion()==null || persona.getOrganizacion().getId()==null){
            JOptionPane.showMessageDialog(null, "Seleccionar la Organizacion de la Persona", "Error", JOptionPane.ERROR_MESSAGE);
            resultado = false;
        }
        return resultado;
    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void windowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowActivated
        // TODO add your handling code here:
        if (readOnly) {
            jTextFieldApellido.setEditable(false);
            jTextFieldNombre.setEditable(false);
            jTextFieldNroDoc.setEditable(false);
            jFormattedTextFieldFechaNac.setEditable(false);
            jComboBoxEstadoCivil.setEnabled(false);
            jComboBoxNacionalidad.setEnabled(false);
            jButtonBuscarOrganizacion.setVisible(false);
            jComboBoxTipoDocumento.setEnabled(false);
            jButtonGuardar.setVisible(false);
            jButtonCargarFoto.setVisible(false);
        }
        if (persona.getId() == null) {
            jPanelAntecedentes.setEnabled(false);
        }


    }//GEN-LAST:event_windowActivated

    private void jButtonCargarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarFotoActionPerformed
        // TODO add your handling code here:
        File input;
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            RandomAccessFile f;
            byte[] fotografiaByte = null;

            try {
                f = new RandomAccessFile(chooser.getSelectedFile(), "r");
                fotografiaByte = new byte[(int) f.length()];
                f.read(fotografiaByte);
                persona.setFotografia(fotografiaByte);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                BufferedImage image = ImageIO.read(chooser.getSelectedFile());
                iconoFoto = new javax.swing.ImageIcon(image);
                jLabel3.setIcon(iconoFoto);
            } catch (IOException ex) {
                Logger.getLogger(JDialogPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonCargarFotoActionPerformed

    private void jButtonBuscarOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarOrganizacionActionPerformed
        // TODO add your handling code here:
        JInternalFrameOrganizacion jFrameOrganizacion = new JInternalFrameOrganizacion();
        jFrameOrganizacion.setModoBuscador(true);
        jFrameOrganizacion.setVisible(true);
        JDialogBuscador buscador=new JDialogBuscador(null, rootPaneCheckingEnabled);
        buscador.setSize(jFrameOrganizacion.getSize());
        jFrameOrganizacion.setClosable(false);
        jFrameOrganizacion.setResizable(false);
        jFrameOrganizacion.setTitle("Buscador de organizaciones");
        buscador.getjDesktopPaneBuscador().add(jFrameOrganizacion);
        buscador.setVisible(true);
        if(jFrameOrganizacion.getOrganizacionSeleccionada()!=null){
        persona.setOrganizacion(jFrameOrganizacion.getOrganizacionSeleccionada());
        jTextFieldOrganizacion.setText(persona.getOrganizacion().getNombre());}
    }//GEN-LAST:event_jButtonBuscarOrganizacionActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPersona dialog = new JDialogPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarOrganizacion;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarFoto;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevoNacionalidad;
    private javax.swing.JButton jButtonNuevoTipoDoc;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxNacionalidad;
    private javax.swing.JComboBox jComboBoxTipoDocumento;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelEstCiv;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelNAcion;
    private javax.swing.JLabel jLabelNomb;
    private javax.swing.JLabel jLabelNroD;
    private javax.swing.JLabel jLabelOrgCont;
    private javax.swing.JLabel jLabelOrgDes;
    private javax.swing.JLabel jLabelOrgDirec;
    private javax.swing.JLabel jLabelOrgTelef;
    private javax.swing.JLabel jLabelOrganizacion;
    private javax.swing.JLabel jLabelOrganizacion1;
    private javax.swing.JLabel jLabelTipDoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAntecedentes;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelFotografia;
    private javax.swing.JPanel jPanelOrganizacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPanePersona;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNroDoc;
    private javax.swing.JTextField jTextFieldOrgContac;
    private javax.swing.JTextField jTextFieldOrgDesc;
    private javax.swing.JTextField jTextFieldOrgDir;
    private javax.swing.JTextField jTextFieldOrgTelef;
    private javax.swing.JTextField jTextFieldOrganizacion;
    private java.util.List listAntecedentes;
    private java.util.List listNacionalidades;
    private java.util.List listOrganizaciones;
    private java.util.List listTipoDocumento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
